---
- name: Get list of repos
  ansible.builtin.uri:
    url: "https://{{ lookup('ansible.builtin.env', 'GIT_URL_SECURE', default=Undefined) }}/api/v4/groups/{{ gitlab_puller_group_id }}/projects?per_page=1024&include_subgroups=true"
    method: GET
    status_code:
      - 200
    return_content: true
    body_format: json
    headers:
      Content-Type: application/json
      PRIVATE-TOKEN: "{{ lookup('ansible.builtin.env', 'GIT_PASSWORD_SECURE', default=Undefined) }}"
    validate_certs: false
  register: result

- name: Clone repositories into workdir
  ansible.builtin.git:
    repo: "{{ item.web_url }}"
    dest: "{{ workdir }}/{{ item.path_with_namespace }}"
    version: "{{ item.default_branch }}"
  loop: "{{ result.json }}"
  loop_control:
    label: "{{ item.name_with_namespace }} - {{ item.default_branch }}"
