---
- name: Push service
  ansible.builtin.copy:
    src: "roles/haproxy/files/haproxy.service"
    dest: "/usr/lib/systemd/system/haproxy.service"
    owner: haproxy
    group: haproxy
    mode: '0640'

- name: Enable and restart haproxy service
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true
    daemon_reload: true

- name: Validate haproxy port
  ansible.builtin.uri:
    url: "https://{{ ansible_host }}"
    validate_certs: false
    method: GET
    status_code: 
      - 200
      - 404
      - 503
  register: haproxy_response

- name: Debug response
  ansible.builtin.debug:
    var: haproxy_response
