---
- name: Push Dockerfile
  ansible.builtin.copy:
    src: "roles/haproxy/files/Dockerfile"
    dest: "/tmp/haproxy/Dockerfile"
    mode: '0640'

- name: Build an image locally usage
  community.docker.docker_image:
    build:
      path: "/tmp/haproxy"
    name: "haproxy-custom"
    tag: "{{ img_tag }}"
    push: false
    source: build

- name: Run lint
  ansible.builtin.command: "docker run haproxy-custom:{{ img_tag }} -c -f /etc/haproxy/haproxy.cfg"
  register: haproxy_lint
  changed_when: haproxy_lint.rc == 0
  failed_when: haproxy_lint.rc != 0

- name: Re-create a container
  community.docker.docker_container:
    name: "haproxy-custom"
    image: "haproxy-custom:{{ img_tag }}"
    restart_policy: always
    network_mode: host
    state: started
    restart: true
