---
- name: Print distribution
  ansible.builtin.debug:
    var: ansible_distribution

- name: Install haproxy
  ansible.builtin.yum:
    name: haproxy
  when:
    - ansible_distribution == "CentOS" or ansible_distribution == "AlmaLinux"

- name: Install haproxy
  ansible.builtin.apt:
    name: haproxy
  when:
    - ansible_distribution == "Ubuntu"
