---
- name: Install centos
  ansible.builtin.import_tasks: ./install-centos.yml
  tags:
    - centos
    - systemd

- name: Prepare
  ansible.builtin.import_tasks: ./prepare.yml
  tags:
    - prepare
    - docker
    - systemd

- name: Deploy docker
  ansible.builtin.import_tasks: ./deploy-docker.yml
  tags:
    - docker

- name: Deploy systemd
  ansible.builtin.import_tasks: ./deploy-systemd.yml
  tags:
    - systemd
