---
- name: Disable SELinux
  selinux: 
    state: disabled

- name: Install haproxy
  yum:
    name: haproxy

- name: Push temp configuration
  copy:
    src: ./roles/haproxy/files/haproxy.cfg
    dest: /etc/haproxy/haproxy_temp.cfg

- name: Check config
  command: haproxy -f /etc/haproxy/haproxy_temp.cfg -c

- name: Push configuration
  copy:
    src: ./roles/haproxy/files/haproxy.cfg
    dest: /etc/haproxy/haproxy.cfg

- name: Push service
  copy:
    src: ./roles/haproxy/files/haproxy.service
    dest: /usr/lib/systemd/system/haproxy.service

- name: Enable and restart haproxy service
  systemd:
    name: haproxy
    state: restarted
    enabled: yes
    daemon_reload: yes
