---
- name: Install centos
  ansible.builtin.import_tasks: ./install-centos.yml

- name: Prepare
  ansible.builtin.import_tasks: ./prepare.yml

#- name: Deploy docker
#  ansible.builtin.import_tasks: ./deploy-docker.yml

- name: Deploy systemd
  ansible.builtin.import_tasks: ./deploy-systemd.yml
