---
# tasks file for haproxy
- name: Install haproxy
  ansible.builtin.yum:
    name: haproxy

- name: Push prepared certificate in pem format
  copy:
    content: "{{ hostvars['CERTIFICATE']['vnmntn.com'] }}" 
    dest: /etc/ssl/certs/vnmntn.com.pem
    owner: haproxy
    mode: 0640

- name: Push dhparams in pem format
  copy:
    content: "{{ hostvars['CERTIFICATE']['dhparams'] }}" 
    dest: /etc/haproxy/dhparams.pem
    owner: haproxy
    mode: 0640

- name: Push temp configuration
  ansible.builtin.copy:
    src: "roles/haproxy/files/haproxy.cfg"
    dest: "/etc/haproxy/haproxy_temp.cfg"
    owner: haproxy
    group: haproxy
    mode: 0640

- name: Check config
  ansible.builtin.command: haproxy -f /etc/haproxy/haproxy_temp.cfg -c
  register: validation_result
  changed_when: "'Fatal errors found in configuration' not in validation_result.stderr"

- name: Push configuration
  ansible.builtin.copy:
    src: "roles/haproxy/files/haproxy.cfg"
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    group: haproxy
    mode: 0640

- name: Push service
  ansible.builtin.copy:
    src: "roles/haproxy/files/haproxy.service"
    dest: "/usr/lib/systemd/system/haproxy.service"
    owner: haproxy
    group: haproxy
    mode: 0640

- name: Enable and restart haproxy service
  ansible.builtin.systemd:
    name: haproxy
    state: restarted
    enabled: true
    daemon_reload: true
