---
- name: Push prepared certificate in pem format
  ansible.builtin.copy:
    content: "{{ hostvars['CERTIFICATE']['mycert'] }}"
    dest: "{{ confdir }}/haproxy/wildcard.pem"
    owner: "{{ owner }}"
    mode: '0640'

- name: Push dhparams in pem format
  ansible.builtin.copy:
    content: "{{ hostvars['CERTIFICATE']['dhparams'] }}"
    dest: "{{ confdir }}/haproxy/dhparams.pem"
    owner: "{{ owner }}"
    mode: '0640'

- name: Push configuration
  ansible.builtin.copy:
    content: "{{ hostvars['CERTIFICATE']['haproxy_cfg'] }}"
    dest: "{{ confdir }}/haproxy/haproxy.cfg"
    owner: "{{ owner }}"
    mode: '0640'
