---
- name: Create haproxy directory if does not exists
  ansible.builtin.file:
    path: "/tmp/haproxy"
    state: directory
    mode: '0640'

- name: Push prepared certificate in pem format
  ansible.builtin.copy:
    content: "{{ hostvars['CERTIFICATE']['mycert'] }}"
    dest: "/tmp/haproxy/wildcard.pem"
    owner: haproxy
    mode: '0640'

- name: Push dhparams in pem format
  ansible.builtin.copy:
    content: "{{ hostvars['CERTIFICATE']['dhparams'] }}"
    dest: "/tmp/haproxy/dhparams.pem"
    owner: haproxy
    mode: '0640'

- name: Push configuration
  ansible.builtin.copy:
    src: "roles/haproxy/files/haproxy.cfg"
    dest: "/tmp/haproxy/haproxy.cfg"
    owner: haproxy
    group: haproxy
    mode: '0640'
