---
- name: Push temp configuration
  ansible.builtin.copy:
    src: "roles/haproxy/files/haproxy.cfg"
    dest: "/tmp/haproxy/haproxy_temp.cfg"
    owner: haproxy
    group: haproxy
    mode: '0640'

- name: Check config
  ansible.builtin.command: "haproxy -f /etc/haproxy/haproxy_temp.cfg -c"
  register: validation_result
  changed_when: "'Fatal errors found in configuration' not in validation_result.stderr"
