---
auditbeat.modules:
  - module: auditd
    audit_rule_files: ['${path.config}/audit.rules.d/*.conf']
    audit_rules: |
  - module: file_integrity
    paths:
      - /bin
      - /usr/bin
      - /sbin
      - /usr/sbin
      - /etc
  - module: system
    datasets:
      - package
    period: 2m 
  - module: system
    datasets:
      - host    
      - login   
      - process 
      - socket  
      - user    
    state.period: 12h
    user.detect_password_changes: true
    login.wtmp_file_pattern: /var/log/wtmp*
    login.btmp_file_pattern: /var/log/btmp*
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
  - add_docker_metadata: ~
output.kafka:
  hosts: ["kafka:9092"]
  topic: "auditbeat-logs"
  topics:
    - topic: "auditbeat-critical"
      when.contains:
        message: "CRITICAL"
    - topic: "auditbeat-error"
      when.contains:
        message: "ERR"
