---
driver:
  name: docker

platforms:
  - name: test-wg-ubuntu2004
    box: generic/ubuntu2004
    interfaces:
      - auto_config: true
        network_name: private_network
        type: static
        ip: 192.168.122.16
    groups:
      - postgres
      - databases

provisioner:
  name: ansible
  log: true
  options:
    diff: true
  config_options:
    defaults:
      stdout_callback: yaml
      force_color: true
  lint:
    name: ansible-lint
    options:
      force-color: true
verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - lint
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - check
    - converge
    - idempotence
    - check
    - verify
    - cleanup
    - destroy
