---
kind: pipeline
type: kubernetes
name: kube

steps:
- name: check kube api
  image: dtzar/helm-kubectl
  commands:
    - kubectl --server $K8S_SERVER --token $K8S_TOKEN get ns --insecure-skip-tls-verify
  environment:
    K8S_SERVER:
      from_secret: K8S_SERVER
    K8S_TOKEN:
      from_secret: K8S_TOKEN
  when:
    branch:
      - master
    event:
      - push

- name: deploy postgres custom
  image: dtzar/helm-kubectl
  commands:
    - helm repo add bitnami https://charts.bitnami.com/bitnami
    - helm repo update
    - helm search repo postgresql
    - helm upgrade 
      --kube-apiserver $K8S_SERVER 
      --kube-token $K8S_TOKEN 
      --kube-insecure-skip-tls-verify
      --install
      --namespace dev
      --create-namespace
      postgresql-custom bitnami/postgresql
      --set auth.username=$PG_CUSTOM_USER
      --set auth.password=$PG_CUSTOM_PASSWORD
      --set auth.database=$PG_CUSTOM_DB
  environment:
    K8S_SERVER:
      from_secret: K8S_SERVER
    K8S_TOKEN:
      from_secret: K8S_TOKEN
  when:
    branch:
      - master
    event:
      - push

---
kind: pipeline
type: kubernetes
name: ansible

steps:
- name: ansible lint
  image: alpine:3.17
  commands:
    - apk add git ansible ansible-lint
    - ansible-galaxy collection install ansible.posix
    - ansible-galaxy collection install community.general
    - ansible-lint *.yml
  when:
    branch:
      - master
    event:
      - push 

- name: markdown lint
  image: node:18
  commands:
    - npm i -g markdownlint-cli
    - find . | grep "\.md" | xargs -I % sh -c "markdownlint %"
  when:
    branch:
      - master
    event:
      - push 

#- name: run init role
#  image: alpine
#  commands:
#    - apk add ansible
#    - ansible-playbook init.yml
#  when:
#    branch:
#      - master
#    event:
#      - push 
