---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  commands:
    - docker build . -t ansible-lint

- name: tarantool test
  commands:
    - ansible-playbook ./tarantool-local.yml --tags database
