---
kind: pipeline
type: kubernetes
name: default

steps:
- name: lint
  image: archlinux
  commands:
  - pacman -Syyu git ansible-lint --noconfirm
  - ansible-lint *.yml
  - ansible-lint playbooks/*.yml

- name: init role
  image: archlinux
  commands:
    - pacman -Syyu ansible --noconfirm
    - ansible-playbook init.yml
