---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: greeting
  commands:
  - docker build . -t ansible-lint

services:
- name: database
  image: mysql
  ports:
  - 3306

