---
kind: pipeline
type: kubernetes
name: lint and test

steps:
- name: lint
  image: alpine:3.17
  commands:
  - apk add ansible-lint
  - ansible-lint ./cluster-network.yml
  - ansible-lint ./sshd.yml
  - ansible-lint ./wireguard.yml
  when:
    branch:
      - master
    event:
      - push 

- name: test init alpine
  image: alpine:3.17
  commands:
    - apk add ansible
    - ansible-playbook init.yml
  when:
    branch:
      - master
    event:
      - push 

- name: test init archlinux
  image: archlinux
  commands:
    - pacman -Syyu --noconfirm
    - pacman -S ansible ansible-lint --noconfirm
    - ansible-playbook init.yml
  when:
    branch:
      - master
    event:
      - push

---
kind: pipeline
type: docker
name: openldap

steps:
- name: build
  image: docker:dind
  commands:
    - docker build -f ./openldap/Dockerfile . -t openldap
  when:
    branch:
      - master
    event:
      - push 
