---
kind: pipeline
type: kubernetes
name: default

steps:
- name: ansible lint
  image: archlinux
  commands:
    - pacman -Syyu git ansible ansible-lint --noconfirm
    - ansible-galaxy collection install ansible.posix
    - ansible-galaxy collection install community.general
    - ansible-lint *.yml
    - ansible-lint playbooks/*.yml

- name: markdown lint
  image: node:18
  commands:
    - npm i -g markdownlint-cli
    - find . | grep md | xargs -I % sh -c "markdownlint %"

- name: run init role
  image: archlinux
  commands:
    - pacman -Syyu ansible --noconfirm
    - ansible-playbook init.yml
