---
kind: pipeline
type: kubernetes
name: lint and test

steps:
- name: lint
  image: alpine:3.17
  commands:
  - apk add ansible-lint
  - ansible-lint ./cluster-network.yml
  - ansible-lint ./sshd.yml
  - ansible-lint ./wireguard.yml

- name: test init alpine
  image: alpine:3.17
  commands:
    - apk add ansible
    - ansible-playbook init.yml

- name: test init archlinux
  image: archlinux
  commands:
    - pacman -Syyu --noconfirm
    - pacman -S ansible ansible-lint --noconfirm
    - ansible-playbook init.yml

---
kind: pipeline
name: docker

steps:
- name: test
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - sleep 5 # give docker enough time to start
  - docker ps

services:
- name: docker
  image: docker:dind
  privileged: true
  volumes:
  - name: dockersock
    path: /var/run

volumes:
- name: dockersock
  temp: {}
