---
kind: pipeline
type: kubernetes
name: default

steps:
- name: ansible lint
  image: alpine:3.17
  commands:
    - apk add git ansible ansible-lint
    - ansible-galaxy collection install ansible.posix
    - ansible-galaxy collection install community.general
    - ansible-lint *.yml
    - ansible-lint playbooks/*.yml

- name: markdown lint
  image: node:18
  commands:
    - npm i -g markdownlint-cli
    - find . | grep "\.md" | xargs -I % sh -c "markdownlint %"

- name: run init role
  image: archlinux
  commands:
    - apk add ansible
    - ansible-playbook init.yml
