---
kind: pipeline
type: docker
name: default

steps:
- name: ansible-lint
  image: alpine
  commands:
    - apk add git ansible ansible-lint
    - ansible-galaxy collection install ansible.posix
    - ansible-galaxy collection install community.general
    - ansible-lint *.yml

- name: markdownlint
  image: alpine
  commands:
    - apk add npm
    - npm i -g markdownlint-cli
    - find . | grep "\.md" | xargs -I % sh -c "markdownlint %"
