---
kind: pipeline
type: exec
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: deploy tarantool in docker
  commands:
    - cd ./roles/tarantool/files 
    - docker-compose up -d
  environment:
    KEYCLOAK_HOSTNAME:
      from_secret: KEYCLOAK_HOSTNAME
---
kind: pipeline
type: exec
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  commands:
    - docker build . -t ansible-lint
