---
kind: pipeline
type: kubernetes
name: default

steps:
- name: lint
  image: alpine:3.17
  commands:
  - apk add py3-pip gcc
  - pip3 install ansible-lint
  - ansible-lint *.yml
- name: test init alpine
  image: alpine:3.17
  commands:
    - apk add py3-pip
    - pip3 install ansible
    - ansible-playbook init.yml
