---
stages:
  - lint
  - localinstall

ansiblelint:
  stage: lint
  image: alpine:3.17
  script:
    - apk add git ansible ansible-lint
    - ansible-galaxy collection install ansible.posix
    - ansible-galaxy collection install community.general
    - ansible-lint *.yml
  tags:
    - docker

markdownlint:
  stage: lint
  image: alpine:3.17
  script:
    - apk add npm
    - npm i -g markdownlint-cli
    - find . | grep "\.md" | xargs -I % sh -c "markdownlint %"
  tags:
    - docker

alpine-localinstall:
  stage: localinstall
  image: alpine
  script:
    - apk add ansible
    - ansible-playbook localhost.yml
  tags:
    - docker
  when: manual
  only:
    - master

archlinux-localinstall:
  stage: localinstall
  image: archlinux
  script:
    - pacman -Syyu ansible --noconfirm
    - ansible-playbook localhost.yml
  tags:
    - docker
  when: manual
  only:
    - master
