---
- name: clone repositories
  hosts: 127.0.0.1
  gather_facts: false
  connection: local
  tasks:
    - name: clone repository by example
      git:
        repo: "git@github.com:alexmalder/{{ item }}"
        dest: "~/GitHub/{{ item }}"
        version: master
      with_items:
        - openldap
        - helm-deployment
        - helm-job
        - salt
        - audit
        - raw-tcp
        - kanban
