---
stages:
  - lint
  - test

ansiblelint:
  stage: lint
  image: alpine:3.17
  script:
    - apk add git ansible ansible-lint
    - ansible-galaxy collection install ansible.posix
    - ansible-galaxy collection install community.general
    - ansible-lint *.yml
  tags:
    - docker
  only:
    - master

markdownlint:
  stage: lint
  image: alpine:3.17
  script:
    - apk add npm
    - npm i -g markdownlint-cli
    - find . | grep "\.md" | xargs -I % sh -c "markdownlint %"
  tags:
    - docker
  only:
    - master

ansible-playbook:
  stage: test
  image: alpine:3.17
  script:
    - apk add ansible
    - ansible-playbook init.yml
  tags:
    - docker
  when: manual
  only:
    - master
