---
- name: Common play
  hosts: hypervisor
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux:
        state: disabled

    - name: Remove ugly packages
      ansible.builtin.yum:
        name:
          - firewalld
        state: absent

    - name: Install epel release
      ansible.builtin.yum:
        name: epel-release

    - name: Install admin tools
      ansible.builtin.yum:
        name: "{{ item }}"
      with_items:
        - git
        - unzip
        - tar
        - yum-utils
        - ncdu
        - tmux
        - net-tools
        - htop
        - vim
        - wget
        - nnn

#    - name: Import role ssh
#      ansible.builtin.import_role:
#        name: sshd
