---
- name: Register secrets and generate local files
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register inventory
      ansible.builtin.command: pass show ansible/inventory/inventory.yaml
      register: inventory_yaml
      changed_when: inventory_yaml.rc == 0
      failed_when: inventory_yaml.rc != 0

    - name: Register netrc
      ansible.builtin.command: pass show ansible/git/netrc
      register: netrc
      changed_when: netrc.rc == 0
      failed_when: netrc.rc != 0

    - name: Register netrc.fish
      ansible.builtin.command: pass show ansible/git/netrc.fish
      register: netrc_fish
      changed_when: netrc_fish.rc == 0
      failed_when: netrc_fish.rc != 0

    - name: Register ssh config
      ansible.builtin.command: pass show ansible/ssh/config
      register: ssh_config
      changed_when: ssh_config.rc == 0
      failed_when: ssh_config.rc != 0

#    - name: Set facts from pass
#      ansible.builtin.set_fact:
#        inventory: "{{ inventory_yaml.stdout }}"
#        netrc: "{{ netrc.stdout }}"
#        netrc_fish: "{{ netrc_fish.stdout }}"

    - name: Generate netrc
      ansible.builtin.copy:
        content: "{{ netrc.stdout }}"
        dest: ~/.netrc
        mode: '0600'

    - name: Generate git creds for fish
      ansible.builtin.copy:
        content: "{{ netrc_fish.stdout }}"
        dest: ~/.config/fish/conf.d/netrc.fish
        mode: '0600'

    - name: Create inventory
      ansible.builtin.file:
        path: ./inventory
        state: directory
        mode: '0700'

    - name: Save inventory to inventory directory
      ansible.builtin.copy:
        content: "{{ inventory_yaml.stdout }}"
        dest: ./inventory/inventory.yaml
        mode: '0600'

    - name: Generate ssh config
      ansible.builtin.copy:
        content: "{{ ssh_config.stdout }}"
        dest: ~/.ssh/config
        mode: '0600'

#    - name: Generate hosts file
#      ansible.builtin.copy:
#        src: templates/hosts
#        dest: /etc/hosts
#        mode: '0644'
#      become: true
