---
- name: Register secrets and generate local files
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register inventory
      ansible.builtin.command: pass show ansible/inventory.yaml
      register: inventory_yaml
      changed_when: inventory_yaml.rc == 0
      failed_when: inventory_yaml.rc != 0

    - name: Register netrc
      ansible.builtin.command: pass show ansible/netrc.yml
      register: netrc_yml
      changed_when: netrc_yml.rc == 0
      failed_when: netrc_yml.rc != 0

    - name: Register ansible config
      ansible.builtin.command: pass show ansible/ansible.cfg
      register: ansible_cfg
      changed_when: ansible_cfg.rc == 0
      failed_when: ansible_cfg.rc != 0

    - name: Set facts from pass
      ansible.builtin.set_fact:
        inventory: "{{ inventory_yaml.stdout | from_yaml }}"
        netrc: "{{ netrc_yml.stdout | from_yaml }}"

    - name: Generate netrc
      ansible.builtin.template:
        src: templates/netrc.jinja
        dest: ~/.netrc
        mode: '0600'

    - name: Generate git creds for fish
      ansible.builtin.template:
        src: templates/env.fish.jinja
        dest: ~/.config/fish/conf.d/netrc.fish
        mode: '0600'

    - name: Create inventory
      ansible.builtin.file:
        path: ./inventory
        state: directory
        mode: '0700'

    - name: Save inventory to inventory directory
      ansible.builtin.copy:
        content: "{{ inventory_yaml.stdout }}"
        dest: ./inventory/inventory.yaml
        mode: '0600'

    - name: Save ansible_cfg
      ansible.builtin.copy:
        content: "{{ ansible_cfg.stdout }}"
        dest: ./ansible.cfg
        mode: '0600'

    - name: Generate ssh config
      ansible.builtin.template:
        src: templates/ssh_config.jinja
        dest: ~/.ssh/config
        mode: '0600'
