---
- name: Generate wireguard configuration locally
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register secure variables
      ansible.builtin.command: pass show ansible/inventory.yaml
      register: inventory_yaml
      changed_when: inventory_yaml.rc == 0
      failed_when: inventory_yaml.rc != 0

    - name: Set fact from secure variables
      ansible.builtin.set_fact:
        inventory: "{{ inventory_yaml.stdout | from_yaml }}"

    - name: Debug config
      debug:
        var: inventory
