---
- hosts: docker
  vars:
    registry: gitlab-registry.vnmntn.com:9443/alexmalder/observability
    images:
      - image: quay.io/prometheus/alertmanager 
        tag: v0.25.0
      - image: quay.io/prometheus-operator/prometheus-config-reloader 
        tag: v0.62.0
      - image: quay.io/kiwigrid/k8s-sidecar 
        tag: 1.22.0
      - image: grafana/grafana 
        tag: 9.3.1
      - image: registry.k8s.io/kube-state-metrics/kube-state-metrics 
        tag: v2.7.0
      - image: quay.io/prometheus-operator/prometheus-operator 
        tag: v0.62.0
      - image: quay.io/prometheus/node-exporter 
        tag: v1.5.0
      - image: grafana/loki 
        tag: 2.6.1
      - image: docker.io/grafana/promtail 
        tag: 2.7.0
      - image: quay.io/prometheus/prometheus 
        tag: v2.41.0
    dev:
      - image: python 
        tag: 3.8
      - image: apache/superset
        tag: latest
      - image: ldapaccountmanager/lam
        tag: stable
      - image: bitnami/openldap
        tag: 2.6

  tasks:
    - name: Install docker python module | docker-clone
      ansible.builtin.pip:
        name:
          - docker

    - name: Tag and push to private registry | docker-clone
      community.docker.docker_image:
        name: "{{ item.image }}:{{ item.tag }}"
        repository: "{{ registry }}/{{ item.image.split('/')[-1] }}"
        tag: "{{ item.tag }}"
        push: true
        source: pull
      with_items: "{{ images }}"
