---
- name: Include variables
  hosts: hypervisor
  vars:
    registry: git.vnmntn.com/alexmalder
    images:
      - image: apache/superset
        tag: latest
      - image: docker.io/bitnami/memcached
        tag: 1.6.9-debian-10-r114
      - image: docker.io/bitnami/postgresql
        tag: 11.11.0-debian-10-r62
      - image: docker.io/bitnami/postgresql
        tag: 14.6.0-debian-11-r13
      - image: docker.io/bitnami/postgresql
        tag: 15.1.0-debian-11-r12
      - image: docker.io/bitnami/postgresql
        tag: 15.1.0-debian-11-r20
      - image: docker.io/bitnami/redis
        tag: 7.0.7-debian-11-r0
      - image: docker.io/drone/drone
        tag: 2.12.1
      - image: drone/drone-runner-kube
        tag: 1.0.0-rc.3
      - image: gitea/gitea
        tag: 1.17.4
      - image: ldapaccountmanager/lam
        tag: stable
      - image: bitnami/openldap
        tag: 2.6
  tasks:
    - name: Install docker python module
      pip:
        name:
          - docker

    - name: Tag and push to private registry
      community.docker.docker_image:
        name: "{{ item.image }}:{{ item.tag }}"
        repository: "{{ registry }}/{{ item.image.split('/')[-1] }}"
        tag: "{{ item.tag }}"
        push: true
        source: pull
      with_items: "{{ images }}"
