---
- name: Deploy drone-runner in docker-container
  hosts: cloud0
  tasks:
    - name: Install python requirements | drone-runner
      ansible.builtin.pip:
        name:
          - requests
          - docker

    - name: Container present | drone
      community.docker.docker_container:
        name: drone_server
        state: started
        image: drone/drone:2
        restart_policy: always
        published_ports:
          - 127.0.0.1:8443:443
          - 127.0.0.1:8080:80
        env:
          DRONE_GITEA_SERVER: https://git.vnmntn.com
          DRONE_GITEA_CLIENT_ID: f4aaf732-218e-4204-bb6b-ac230b433863
          DRONE_GITEA_CLIENT_SECRET: gto_h6gklli23rfob5uytvkgsic3trmrvd47jt4xlr3txobgmzdt35yq
          DRONE_RPC_SECRET: QACQyoiXKgQ8j7o8sdg
          DRONE_SERVER_HOST: drone.vnmntn.com
          DRONE_SERVER_PROTO: https
        volumes:
          - /var/lib/drone:/data

    - name: Container present | drone-runner
      community.docker.docker_container:
        name: drone-runner-docker-0
        state: started
        image: drone/drone-runner-docker:1
        restart_policy: always
        env:
          DRONE_RPC_PROTO: https
          DRONE_RPC_HOST: drone.vnmntn.com
          DRONE_RPC_SECRET: QACQyoiXKgQ8j7o8sdg
          DRONE_RUNNER_CAPACITY: '2'
          DRONE_RUNNER_NAME: drone-runner-docker-0
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
