---
- name: Deploy drone-runner in docker
  hosts: cloud0
  tasks:
    - name: Install python requirements
      ansible.builtin.pip:
        name:
          - requests
          - docker

    - name: Container present
      community.docker.docker_container:
        name: drone_server
        state: started
        restart: true
        image: drone/drone:2
        restart_policy: always
        published_ports:
          - 127.0.0.1:8443:443
          - 127.0.0.1:8080:80
        env:
          DRONE_GITEA_SERVER: https://git.vnmntn.com
          DRONE_GITEA_CLIENT_ID: fc8ee41a-65b8-403f-b1a8-c44d4870a2ef
          DRONE_GITEA_CLIENT_SECRET: gto_vtpyzhhyia7s76bnmh6wlbsfbis3z2hbwbhfqot3u7day72rawbq
          DRONE_RPC_SECRET: QACQyoiXKgQ8j7o8sdg
          DRONE_SERVER_HOST: drone.vnmntn.com
          DRONE_SERVER_PROTO: https
        volumes:
          - /var/lib/drone:/data
