---
- name: Pull repos from gitlab[owned=true]
  hosts: 127.0.0.1
  connection: local
  vars:
    workdir: "~/Code"
  tasks:
    - name: Include pull gitlab
      ansible.builtin.include_tasks: ./tasks/retrieve-gitlab-group.yml
      with_items:
        - group_id: 2363
        - group_id: 12655
        - group_id: 12106
        - group_id: 11710
        - group_id: 1225
        - group_id: 2267
