---
- name: Pull repos from gitlab[owned=true]
  hosts: 127.0.0.1
  connection: local
  vars:
    params: "owned=true"
  tasks:
    - name: Get list of repos
      ansible.builtin.uri:
        url: "https://{{ GIT_URL }}/api/v4/projects?{{ params }}"
        method: GET
        status_code:
          - 200
        return_content: true
        body_format: json
        headers:
          Content-Type: application/json
          PRIVATE-TOKEN: "{{ PRIVATE_TOKEN }}"
        validate_certs: false
      register: result

    - name: Clone repositories into workdir
      ansible.builtin.git:
        repo: "{{ item.ssh_url_to_repo }}"
        dest: "~/Code/{{ item.ssh_url_to_repo.replace('.git', '').split('/')[-1] }}"
        version: "{{ item.default_branch }}"
      with_items: "{{ result.json }}"
