---
- name: Run gitlab in docker with docker-compose
  hosts: openvpn
  vars:
    bind_ip: 127.0.0.1
    base_domain: 'vnmntn.com'
  tasks:
    - name: Execute docker-compose
      community.docker.docker_compose:
        project_name: gitlab-ldap
        definition:
          version: '3.6'
          services:
            web:
              image: 'gitlab/gitlab-ce:14.10.5-ce.0'
              restart: always
              hostname: 'gitlab.{{ bind_domain }}'
              environment:
                GITLAB_OMNIBUS_CONFIG: |
                  external_url 'https://gitlab.{{ bind_domain }}'
                  registry_external_url "https://gitlab-registry.{{ bind_domain }}:9443"
                  registry_nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.{{ bind_domain }}.crt"
                  registry_nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.{{ bind_domain }}.key"
                  gitlab_rails['ldap_enabled'] = true
                  gitlab_rails['ldap_servers'] = {
                    'main' => {
                      'label' => 'LDAP',
                      'host' =>  'ldap.mydomain.com',
                      'port' => 636,
                      'uid' => 'sAMAccountName',
                      'encryption' => 'simple_tls',
                      'base' => 'dc=example,dc=com',
                    }
                  }
              ports:
                - '{{ bind_ip }}:8443:443'
                - '{{ bind_ip }}:8022:22'
                - '{{ bind_ip }}:9443:9443'
                # - '{{ bind_ip }}:8080:80'
              volumes:
                - 'config:/etc/gitlab'
                - 'logs:/var/log/gitlab'
                - 'data:/var/opt/gitlab'
              shm_size: '256m'
            gitlab-runner:
              image: 'gitlab/gitlab-runner:v14.10.1'
              volumes:
                - /var/run/docker.sock:/var/run/docker.sock
                - gitlab_runner_config:/etc/gitlab-runner
              restart: unless-stopped
          volumes:
            config: null
            logs: null
            data: null
            gitlab_runner_config: null
      register: output
      vars:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Print debug info
      ansible.builtin.debug:
        var: output
