---
- name: Include variables
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register config
      ansible.builtin.command: "pass show ansible/{{ workdir }}/haproxy.cfg"
      register: haproxy_cfg
      changed_when: haproxy_cfg.rc == 0
      failed_when: haproxy_cfg.rc != 0
      tags:
        - docker

    - name: Register mycert
      ansible.builtin.command: "pass show ansible/{{ workdir }}/mycert.pem"
      register: mycert
      changed_when: mycert.rc == 0
      failed_when: mycert.rc != 0
      tags:
        - docker

    - name: Register dhparams_raw
      ansible.builtin.command: "pass show ansible/{{ workdir }}/dhparams.pem"
      register: dhparams_raw
      changed_when: dhparams_raw.rc == 0
      failed_when: dhparams_raw.rc != 0
      tags:
        - docker

    - name: Set facts
      ansible.builtin.set_fact:
        config: "{{ haproxy_cfg.stdout + '\n' }}"
        mycert: "{{ mycert.stdout }}"
        dhparams: "{{ dhparams_raw.stdout }}"
      tags:
        - docker

    - name: Add prepared certificate host variable
      ansible.builtin.add_host:
        haproxy_cfg: "{{ config }}"
        name: CERTIFICATE
        mycert: "{{ mycert }}"
        dhparams: "{{ dhparams }}"
      tags:
        - docker

    - name: Add dhparams host variable
      ansible.builtin.add_host:
        name: CERTIFICATE
      tags:
        - docker

- name: Setup haproxy
  gather_facts: false
  hosts: cloud0
  become: true
  roles:
    - name: Use haproxy role
      role: haproxy
