---
- name: Include variables
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register mycert
      ansible.builtin.command: "pass show ansible/haproxy/mycert.pem"
      register: mycert
      changed_when: mycert.rc == 0
      failed_when: mycert.rc != 0
      tags: [docker]

    - name: Register dhparams_raw
      ansible.builtin.command: "pass show ansible/dhparams.pem"
      register: dhparams_raw
      changed_when: dhparams_raw.rc == 0
      failed_when: dhparams_raw.rc != 0
      tags: [docker]

    - name: Set facts
      ansible.builtin.set_fact:
        mycert: "{{ mycert.stdout }}"
        dhparams: "{{ dhparams_raw.stdout }}"
      tags: [docker]

    - name: Add prepared certificate host variable
      ansible.builtin.add_host:
        name: CERTIFICATE
        mycert: "{{ mycert }}"
      tags: [docker]

    - name: Add dhparams host variable
      ansible.builtin.add_host:
        name: CERTIFICATE
        dhparams: "{{ dhparams }}"
      tags: [docker]

- name: Setup haproxy
  gather_facts: false
  hosts: cloud0
  roles:
    - name: Use haproxy role
      role: haproxy
