---
- name: Include variables
  gather_facts: no
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register fullchain_raw
      command: 'pass show live/vnmntn.com/fullchain.pem'
      register: fullchain_raw
      changed_when: fullchain_raw.rc == 0
      failed_when: fullchain_raw.rc != 0

    - name: Register privkey_raw
      command: 'pass show live/vnmntn.com/privkey.pem'
      register: privkey_raw
      changed_when: privkey_raw.rc == 0
      failed_when: privkey_raw.rc != 0

    - name: Register dhparams_raw
      command: 'pass show live/dhparams.pem'
      register: dhparams_raw
      changed_when: dhparams_raw.rc == 0
      failed_when: dhparams_raw.rc != 0

    - name: Set fact fullchain
      set_fact: 
        fullchain: "{{ fullchain_raw.stdout }}"

    - name: Set fact privkey
      set_fact: 
        privkey: "{{ privkey_raw.stdout }}"

    - name: Set fact dhparams
      set_fact: 
        dhparams: "{{ dhparams_raw.stdout }}"

    - name: Add prepared certificate host variable
      add_host:
        name: CERTIFICATE
        vnmntn.com:  "{{ fullchain + privkey }}"

    - name: Add dhparams host variable
      add_host:
        name: CERTIFICATE
        dhparams:  "{{ dhparams }}"

- name: Setup haproxy
  gather_facts: no
  hosts: hypervisor
  tasks:
    - name: Debug hostvars['CERTIFICATE']
      debug:
        var: hostvars['CERTIFICATE']
  roles:
    - name: Use haproxy role
      role: haproxy
