---
- name: Macports installer
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Install a list of ports
      community.general.macports:
        name: "{{ item }}"
      with_items:
        - tmux
        - htop
        - wget
        - nnn
        - zsh
        - tmux
        - mc
        - neovim
        - git
        - colordiff
        - fzf
        - ripgrep
        - exa
        - helm-3.11
        - k9s
        - bottom
        - pass
        - wireguard-tools
        - nmap
        - iftop
        - cargo
        - nodejs18
        - npm9
        - yamllint
        - py-ansible
        - ansible-lint
        - ctop
        - dbeaver-community

    - name: port select
      command: "sudo port select --set {{ item.target }} {{ item.source }}"
      with_items:
        - target: helm
          source: helm3.11
        - target: python
          source: python311
        - target: python3 
          source: python311

#    - name: Install node packages
#      community.general.npm:
#        global: true
#        name: "{{ item }}"
#      with_items:
#        - pyright
#        - bash-language-server
#        - yaml-language-server
#        - markdownlint-cli
