---
- name: Macports installer
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    - name: Install a list of ports
      community.general.macports:
        name: "{{ item }}"
      with_items:
        - tmux
        - htop
        - wget
        - nnn
        - zsh
        - tmux
        - mc
        - neovim
        - git
        - colordiff
        - fzf
        - ripgrep
        - exa
        - helm-3.11
        - k9s
        - bottom
        - pass
        - wireguard-tools
        - nmap
        - iftop
        - cargo
        - nodejs18
        - npm9
        - yamllint
        - py-ansible
        - ansible-lint
        - ctop
        - dbeaver-community
