---
- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    npm_packages:
      - markdownlint-cli
      - bash-language-server
      - yaml-language-server
      - pyright
    macports_packages:
      - neovim
      - neofetch
      - fish
      - fzf
      - ripgrep
      - pass
      - eza
      - nnn
      - k9s
      - ctop
      - colordiff
      - npm10
      - cargo
      - glab
      - jq
      - yq
      - zoxide
      - poppler
      - pandoc
      - texlive-fonts-recommended
  tasks:
    - name: Install macports packages
      community.general.macports:
        name: "{{ item }}"
      loop: "{{ macports_packages }}"

    - name: Install npm packages
      community.general.npm:
        name: "{{ item }}"
        global: true
      loop: "{{ npm_packages }}"

    - name: Upgrade macports packages
      community.general.macports:
        name: "{{ macports_packages }}"
        selfupdate: true
        upgrade: true

