---
- name: Macports installer
  hosts: 127.0.0.1
  connection: local
  become: yes
  tasks:
    - name: Install a list of ports
      community.general.macports:
        name: "{{ item }}"
      with_items:
        - tmux
        - htop
        - wget
        - nnn
        - zsh
        - tmux
        - mc
        - neovim
        - git
        - colordiff
        - fzf
        - ripgrep
        - exa
        - helm-3.11
        - k9s
        - bottom
        - pass
        - wireguard-tools
        - nodejs18
        - nmap
        - iftop
