---
- hosts: gr-test
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create a k8s namespace
      kubernetes.core.k8s:
        name: testing
        api_version: v1
        kind: Namespace
        state: present

    - name: Deployment present
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: postgres
            namespace: testing
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: postgres
            template:
              metadata:
                labels:
                  app: postgres
              spec:
                containers:
                  - name: postgres
                    image: postgres:13
                    imagePullPolicy: "IfNotPresent"
                    ports:
                      - containerPort: 5432
                    env:
                    - name: POSTGRES_USER
                      value: postgres
                    - name: POSTGRES_PASSWORD
                      value: postgres
                    - name: POSTGRES_DB
                      value: postgres
