---
- name: Import secure variables to hostvars
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register secure variables
      ansible.builtin.command: pass show ansible/postgres/postgres.yml
      register: postgres
      changed_when: postgres.rc == 0
      failed_when: postgres.rc != 0

    - name: Set fact from secure variables
      ansible.builtin.set_fact:
        postgres_config: "{{ postgres.stdout | from_yaml }}"

    - name: Add host variables
      ansible.builtin.add_host:
        name: POSTGRES
        config: "{{ postgres_config }}"

- name: Install postgres
  hosts: cloud0
  become: yes
  roles:
    - postgres
