---
- name: Validate local configuration files
  hosts: 127.0.0.1
  connection: local
  vars:
    base_src: roles/localhost/files/.config
  tasks:
    - name: Check fish
      ansible.builtin.include_tasks: ./tasks/validate-task.yml
      vars:
        diff_path: fish/conf.d

    - name: Check nvim lua
      ansible.builtin.include_tasks: ./tasks/validate-task.yml
      vars:
        diff_path: nvim/lua

    - name: Check zathura
      ansible.builtin.include_tasks: ./tasks/validate-task.yml
      vars:
        diff_path: zathura
