---
- name: Generate wireguard configuration locally
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register secure variables
      ansible.builtin.command: pass show ansible/wireguard.yml
      register: wireguard
      changed_when: wireguard.rc == 0
      failed_when: wireguard.rc != 0

    - name: Set fact from secure variables
      ansible.builtin.set_fact:
        wg_config: "{{ wireguard.stdout | from_yaml }}"

    - name: Add wireguard host variable
      ansible.builtin.add_host:
        name: WIREGUARD
        client: "{{ wg_config.client }}"
        server: "{{ wg_config.server }}"

    - name: Create wireguard directory if does no exists
      ansible.builtin.file:
        path: "/etc/wireguard"
        state: directory
        mode: '0640'
      become: true

    - name: Generate client config files
      ansible.builtin.template:
        src: "roles/wireguard/templates/client.conf"
        dest: "./wireguard/{{ item.name }}.conf"
        mode: '0660'
      loop: "{{ hostvars['WIREGUARD']['client']['clients'] }}"
      no_log: true
      become: true

- name: Setup wireguard server
  hosts: hypervisor
  roles:
    - name: Use wireguard role
      role: wireguard
