---
bitwarden_container_name: bitwarden-server
bitwarden_image: vaultwarden/server:1.26.0-alpine
bitwarden_ports:
  - 8080:80
bitwarden_volumes:
  - /var/lib/bitwarden:/data
bitwarden_env:
  VIRTUAL_HOST: bitwarden.vnmntn.ru
  DEFAULT_EMAIL: vnmntn@mail.ru
  WEBSOCKET_ENABLED: true
  SIGNUPS_ALLOWED: false
