---
bitwarden_container_name: bitwarden-server
bitwarden_image: vaultwarden/server:1.33.2
bitwarden_ports:
  - 8080:80
bitwarden_volumes:
  - /var/lib/bitwarden:/data
bitwarden_env:
  DOMAIN: https://vnmntn.ru
  DEFAULT_EMAIL: vnmntn@mail.ru
  WEBSOCKET_ENABLED: "true"
  SIGNUPS_ALLOWED: "false"
  ADMIN_TOKEN: "{{ bitwarden_admin_token }}"
