---
raw:
  - floating_modifier $mod
  - default_border none
  - default_floating_border none
  - font pango:Iosevka 10
  - for_window [class=".*"] border pixel 0
  - assign [class="kitty"] term
  - exec --no-startup-id feh --bg-fill ~/.config/i3/purple-19.jpg
  - exec --no-startup-id picom --config ~/.config/picom.conf


setters:
  - $mod Mod4
  - $circle exec ~/.config/i3/circle

# startup:
#   - sudo wpa_supplicant -c /etc/wpa_supplicant/wpa_supplicant.conf -i wlo1

circle:
  - key: x
    command: kitty
    app: kitty
    ws: term

  - key: w 
    command: qutebrowser
    app: qutebrowser
    ws: qutebrowser

  - key: v 
    command: virt-manager
    app: virt-manager
    ws: virt-manager

  - key: d 
    command: "flatpak run md.obsidian.Obsidian"
    app: obsidian
    ws: obsidian

  - key: o
    command: wps
    app: wps
    ws: wps

bindsym:
  - $mod+Return exec kitty
  - $mod+Shift+q kill
  - $mod+j focus left
  - $mod+semicolon focus right
  - $mod+Left focus left
  - $mod+Down focus down
  - $mod+Up focus up
  - $mod+Right focus right
  - $mod+Shift+semicolon move right
  - $mod+Shift+Left move left
  - $mod+Shift+Down move down
  - $mod+Shift+Up move up
  - $mod+Shift+Right move right
  - $mod+h split h
  - $mod+Shift+space floating toggle
  - $mod+space focus mode_toggle
  - $mod+Shift+r restart
  - $mod+r mode resize
  - $mod+g exec dmenu_run -nb '#000000' -sf '#000000' -sb '#909090' -nf '#909090' -fn 'Iosevka Nerd Font-12'
  - $mod+f fullscreen toggle
  - $mod+Shift+p exec deepin-screenshot
