---
# tasks file for configuration
- name: install zi to .config
  git:
    repo: "https://github.com/z-shell/zi"
    dest: "~/.config/zi"
    version: main

- name: Deploy configuration files | DESKTOP
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "roles/configuration/files/.config"
      dest: "~/"
    - src: "roles/configuration/files/.zshrc"
      dest: "~/"
    - src: "roles/configuration/files/.zsh"
      dest: "~/"
    - src: "roles/configuration/files/.clang-format"
      dest: "~/"
    - src: "roles/configuration/files/.tmux.conf"
      dest: "~/"
    - src: "roles/configuration/files/.xinitrc"
      dest: "~/"
    - src: "roles/configuration/files/.Xresources"
      dest: "~/"

- name: Deploy sound configuration file to modprobe for alpine | DESKTOP
  become: true
  copy:
    src: roles/configuration/files/etc/modprobe.d/alsa-alpine.conf
    dest: /etc/modprobe.d/alsa.conf
  when:
    - ansible_distribution == "Alpine"

- name: Deploy sound configuration file to modprobe for archlinux | DESKTOP
  become: true
  copy:
    src: roles/configuration/files/etc/modprobe.d/alsa-archlinux.conf
    dest: /etc/modprobe.d/alsa.conf
  when:
    - ansible_distribution == "Archlinux"

- name: Restart i3 if needed | DESKTOP
  command: i3-msg restart
  when:
    - ansible_distribution == "Archlinux"