---
# tasks file for configuration
- name: install zi to .config
  git:
    repo: "https://github.com/z-shell/zi"
    dest: "~/.config/zi"
    version: main

- name: Deploy configuration files | DESKTOP
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    # CONFIG
    - src: "./.config"
      dest: "~/"
    # HOME
    - src: "./home"
      dest: "~/"

- name: Deploy sound configuration file to modprobe for archlinux | DESKTOP
  become: true
  copy:
    src: roles/configuration/files/etc/modprobe.d/alsa-archlinux.conf
    dest: /etc/modprobe.d/alsa.conf
  when:
    - ansible_distribution == "Archlinux"

- name: Deploy sound configuration file to modprobe for alpine | DESKTOP
  become: true
  copy:
    src: roles/configuration/files/etc/modprobe.d/alsa-alpine.conf
    dest: /etc/modprobe.d/alsa.conf
  when:
    - ansible_distribution == "Alpine"

- name: Clone repositories by example
  git:
    repo: "git@github.com:alexmalder/{{ item }}"
    dest: "~/Github/{{ item }}"
    version: master
  with_items:
    - openldap
    - helm-deployment
    - helm-job
    - salt
    - audit
    - raw-tcp
    - kanban
    - obsidian-vault
    # - i3
    # - store

- name: Restart i3 if needed | DESKTOP
  command: i3-msg restart
  when:
    - ansible_distribution == "Archlinux"