---
all:
  children:
    selectel:
      hosts:
        hyper01:
          ansible_host: 91.206.15.104
          ansible_user: root
          ansible_port: 22
    vm:
      hosts:
        node1:
          ansible_host: 192.168.122.10
        node2:
          ansible_host: 192.168.122.11
        node3:
          ansible_host: 192.168.122.12
        template:
          ansible_host: 192.168.122.100
      vars:
        ansible_user: root
        ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q root@91.206.15.104"'
