---
all:
  children:
    host:
      hosts:
        hypervisor:
          ansible_host: 185.137.234.222
          ansible_user: root
          ansible_port: 22
    vm:
      hosts:
        docker:
          ansible_host: 192.168.122.9
        control-plane:
          ansible_host: 192.168.122.10
        worker:
          ansible_host: 192.168.122.11
      vars:
        ansible_user: root
        ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q root@185.137.234.222"'
