---
all:
  children:
    selectel:
      hosts:
        hypervisor:
          ansible_host: 185.137.234.222
          ansible_user: root
          ansible_port: 22
        home:
          ansible_host: 10.10.10.3
          ansible_user: root
          ansible_port: 22
    vm:
      hosts:
        node1:
          ansible_host: 192.168.122.10
        node2:
          ansible_host: 192.168.122.11
        node3:
          ansible_host: 192.168.122.12
        drone-runner:
          ansible_host: 192.168.122.13
        elasticsearch:
          ansible_host: 192.168.122.14
        template:
          ansible_host: 192.168.122.100
      vars:
        ansible_user: root
        ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22 -W %h:%p -q root@91.206.15.104"'
