---
all:
  children:
    selectel:
      hosts:
        hyper01:
          ansible_host: 91.206.15.104
          ansible_user: root
    vm:
      hosts:
        drone-runner:
          ansible_port: 10010
        dns:
          ansible_port: 10011
        node1:
          ansible_port: 10012
        node2:
          ansible_port: 10013
        node3:
          ansible_port: 10014
      vars:
        ansible_host: 10.10.10.1
        ansible_user: root
