---
all:
  #  hosts:
  #    proxy:
  #      ansible_host: 91.206.15.104
  #      ansible_user: root
  children:
    selectel:
      hosts:
        hyper01:
          ansible_host: 91.206.15.104
          ansible_user: root
          ansible_port: 22022
    vm:
      hosts:
        drone-runner:
          ansible_host: 192.168.122.10
        dns:
          ansible_host: 192.168.122.11
        node1:
          ansible_host: 192.168.122.12
        node2:
          ansible_host: 192.168.122.13
        node3:
          ansible_host: 192.168.122.14
      vars:
        ansible_user: root
        ansible_ssh_common_args: '-o ProxyCommand="ssh -p 22022 -W %h:%p -q root@91.206.15.104"'
