---
- name: Install dependencies | docker-compose
  ansible.builtin.yum:
    name:
      - python38-pip
      - openssl-devel
      - rust
      - cargo

- name: Install setuptools rust | docker-compose
  ansible.builtin.pip:
    name: setuptools-rust
    executable: pip3.8

- name: Install docker compose | docker-compose
  ansible.builtin.pip:
    name: docker-compose
    executable: pip3.8
