---
# @tags: 
# - ci
- name: Install yum utils
  ansible.builtin.yum:
    name: yum-utils

- name: Add repo
  ansible.builtin.command: "yum-config-manager --add-repo {{ docker_ce_url }}"
  register: myoutput
  changed_when: myoutput.rc != 0
  failed_when: myoutput.rc != 0
- name: Install packages
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Setup service
  ansible.builtin.systemd:
    name: docker
    state: restarted
    enabled: true
    daemon_reload: true
