---
- name: Download helm installation script
  ansible.builtin.get_url:
    url: "{{ helm_url }}"
    dest: /tmp/get-helm.sh
    mode: 'a+x'

- name: Execute helm installation script
  ansible.builtin.command: bash /tmp/get-helm.sh
  register: myoutput
  changed_when: myoutput.rc != 0
  failed_when: myoutput.rc != 0
