---
- name: Download helm installation script
  ansible.builtin.get_url:
    url: "https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3"
    dest: /tmp/get-helm.sh
    mode: 'a+x'

- name: Execute helm installation script
  ansible.builtin.command: bash /tmp/get-helm.sh
  register: myoutput
  changed_when: myoutput.rc != 0
  failed_when: myoutput.rc != 0
