---
# centos_stream: http://mirror.truenetwork.ru/centos/8-stream/isos/x86_64/
# image_name: CentOS-Stream-8-x86_64-20221125-boot.iso
- name: Remove the 'firewalld' package
  ansible.builtin.yum:
    name: firewalld
    state: absent
  when:
    - ansible_distribution == "CentOS"

- name: Install the 'Virtualization Host' package group
  ansible.builtin.dnf:
    name: '@Virtualization Host'
    state: present
  when:
    - ansible_distribution == "CentOS"

- name: Install packages
  become: true
  community.general.pacman:
    name:
      - libvirt
      - virt-manager
      - ebtables
      - dnsmasq
      - dmidecode
      - qemu-desktop
    state: present
  when:
    - ansible_distribution == "Archlinux"

- name: Enable and start libvirtd
  become: true
  ansible.builtin.systemd:
    name: libvirtd
    enabled: true
    daemon_reload: true
    state: started

- name: Download 'centos 8 stream' boot image
  ansible.builtin.get_url:
    url: "{{ centos_stream }}/{{ image_name }}"
    dest: "/var/lib/libvirt/images/{{ image_name }}"
    mode: '0660'
