---
- name: Get files
  ansible.builtin.find:
    paths: "{{ base_src }}/{{ diff_path }}"
    recurse: true
    hidden: true
  register: result

- name: Check result files
  ansible.builtin.include_tasks: ./tasks/pull-on-change.yml
  with_items: "{{ result.files }}"
