---
- name: Create user vector if does not exists
  ansible.builtin.user:
    name: vector
    home: /var/lib/vector
    create_home: true

- name: Download vector package
  ansible.builtin.get_url:
    url: "{{ vector_download_url }}/{{ vector_package_name }}"
    dest: /tmp/vector.rpm
    mode: '0660'

- name: Install vector package
  yum:
    name: /tmp/vector.rpm

- name: Copy vector config file
  ansible.builtin.copy:
    src: roles/vector/files/vector.yml
    dest: /etc/vector/vector.yml
    owner: vector
    group: vector
    mode: '0664'

- name: Setup service
  ansible.builtin.systemd:
    name: vector
    state: restarted
    enabled: true
    daemon_reload: true
