alias vim="nvim"
alias :wq!="exit"
alias ff='vim $(fzf)'
alias gs="git status"
alias vim="nvim"
alias cl="clear"
alias s="sudo"
alias exit="echo 'No action'"
bind ^D "echo 'No action'"
alias ctop="docker run --rm -ti --name=ctop --volume /var/run/docker.sock:/var/run/docker.sock:ro quay.io/vektorlab/ctop:0.7.7"
