export VISUAL="nvim"
export EDITOR="nvim"
export NNN_OPENER="nvim"
export FZF_DEFAULT_OPTS="--color=bg+:-1,bg:-1,spinner:0,hl:51"
export FZF_DEFAULT_COMMAND="rg --files --hidden -g !.git"
export GOPATH="$HOME/.go"
export PATH="$PATH:/opt/local/bin"
export PATH="$PATH:$HOME/.go/bin"
export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
export PATH="$PATH:$HOME/Downloads/yandex-cloud/bin"
export PATH="$PATH:$HOME/.cargo/bin"
export PATH="$PATH:/opt/local/flutter/bin"
export PATH="$PATH:/usr/local/bin"
export PATH="$PATH:$HOME/.local/share/nvim/lsp_servers/jdtls/bin"
export PATH="$PATH:$HOME/.dotnet/tools"
export TERM="linux"
export HELM_EXPERIMENTAL_OCI="1"
export DOTNET_ROOT=/opt/local/share/dotnet
#export JAVA_HOME="/Library/Java/JavaVirtualMachines/openjdk17/Contents/Home"

export PASSWORD_STORE_DIR="$HOME/Code/alexmalder/store"
export LANG=en_US.UTF-8
