---
- name: Install base packages
  community.general.pacman:
    name: "{{ localhost_pacman_base_packages }}"

- name: Install dev packages
  community.general.pacman:
    name: "{{ localhost_pacman_dev_packages }}"

- name: Install ops packages
  community.general.pacman:
    name: "{{ localhost_pacman_ops_packages }}"

- name: Install xorg packages
  community.general.pacman:
    name: "{{ localhost_pacman_xorg_packages }}"

- name: Install desktop packages
  community.general.pacman:
    name: "{{ localhost_pacman_desktop_packages }}"

- name: Install node packages
  community.general.npm:
    global: true
    name: "{{ item }}"
  with_items: "{{ localhost_npm_packages }}"
