---
- name: Install base packages
  community.general.pacman:
    name: "{{ localhost_pacman_base_packages }}"
    state: "{{ state }}"
    extra_args: "{{ extra_args }}"

- name: Install dev packages
  community.general.pacman:
    name: "{{ localhost_pacman_dev_packages }}"
    state: "{{ state }}"
    extra_args: "{{ extra_args }}"

- name: Install ops packages
  community.general.pacman:
    name: "{{ localhost_pacman_ops_packages }}"
    state: "{{ state }}"
    extra_args: "{{ extra_args }}"

- name: Install xorg packages
  community.general.pacman:
    name: "{{ localhost_pacman_xorg_packages }}"
    state: "{{ state }}"
    extra_args: "{{ extra_args }}"

- name: Install desktop packages
  community.general.pacman:
    name: "{{ localhost_pacman_desktop_packages }}"
    state: "{{ state }}"
    extra_args: "{{ extra_args }}"

- name: Install node packages
  community.general.npm:
    global: true
    name: "{{ item }}"
  with_items: "{{ localhost_npm_packages }}"
