---
- name: Install base packages
  become: true
  community.general.pacman:
    name:
      - zsh
      - tmux
      - mc
      - ncdu
      - neovim
      - git
      - colordiff
      - net-tools
      - fzf
      - ripgrep
      - exa
      - tree
      - kitty
      - nnn
      - npm
      - cpupower
      - pass
      - unzip
      - netcat
      - bottom
      - htop

- name: Install dev packages
  become: true
  community.general.pacman:
    name:
      - python-pip
      - wireguard-tools
      - make
      - cmake
      - llvm
      - clang
      - dash
      - virt-manager
      # negwm
      - tk
      - dash
      - xdo

- name: Install ops packages
  become: true
  community.general.pacman:
    name:
      - docker
      - go
      - docker-compose
      - ctop
      - k9s
      - glab
      - kubectl
      - helm
      - gopls

- name: Install xorg packages
  become: true
  community.general.pacman:
    name:
      - xorg
      - xorg-server
      - xorg-xinit

- name: Install desktop packages
  become: true
  community.general.pacman:
    name:
      - sof-firmware
      - filezilla
      - font-manager
      - polybar
      - i3-gaps
      - dmenu
      - qutebrowser
      - telegram-desktop
      - evolution
      - xfce4-power-manager
      - nautilus
      - alacritty
      - xdotool
      - rofi
      - gnome-keyring
      - xclip
      - qtcreator
      - deepin-screenshot
      - dunst
      - obsidian
      - feh
      - firefox
      - xf86-input-synaptics
      - picom
      - lxappearance
      # fonts
      - fontconfig
      - ttf-iosevka-nerd
      - ttf-ubuntumono-nerd

- name: Install node packages
  become: true
  community.general.npm:
    global: true
    name: "{{ item }}"
  with_items:
    - pyright
    - pm2
    - bash-language-server
    - yaml-language-server
    - markdownlint-cli
