---
- name: Deploy user configuration files
  ansible.builtin.copy:
    src: "{{ item.src }}"
    dest: "~/"
    mode: '0640'
  with_items:
    - src: "roles/{{ role_name }}/files/.config"
    - src: "roles/{{ role_name }}/files/home/.clang-format"
    - src: "roles/{{ role_name }}/files/home/.tmux.conf"
    - src: "roles/{{ role_name }}/files/home/.xinitrc"
    - src: "roles/{{ role_name }}/files/home/.Xresources"

- name: Deploy sound configuration file to modprobe for alpine
  become: true
  ansible.builtin.copy:
    src: "roles/{{ role_name }}/files/etc/modprobe.d/{{ ansible_distribution }}.conf"
    dest: /etc/modprobe.d/alsa.conf
    owner: root
    mode: '0640'
  when:
    - ansible_distribution == "Archlinux"
