---
# - name: Deploy user configuration files
#   ansible.builtin.copy:
#     src: "{{ item.src }}"
#     dest: "~/"
#     mode: '0640'
#   with_items:
#     - src: "roles/{{ role_name }}/files/.config"
#     - src: "roles/{{ role_name }}/files/home/.clang-format"
#     - src: "roles/{{ role_name }}/files/home/.tmux.conf"
#     - src: "roles/{{ role_name }}/files/home/.xinitrc"
#     - src: "roles/{{ role_name }}/files/home/.Xresources"

- name: Pull configuration files
  ansible.builtin.copy:
    src: "{{ ansible_env.HOME }}/{{ item }}"  
    dest: "roles/localhost/files/{{ item }}"
  with_items: "{{ localhost_dotfiles }}"