---
- name: Get glab tar.gz
  ansible.builtin.get_url:
    url: "{{ glab_binary_url }}/{{ glab_binary_filename }}"
    dest: /tmp
    mode: '0644'

- name: Extract glab
  ansible.builtin.command: "tar -xvf /tmp/{{ glab_binary_filename }} -C /tmp"
  register: extraction_result
  changed_when: extraction_result.rc == 0
  failed_when: extraction_result.rc != 0

- name: Make glab executable
  ansible.builtin.copy:
    src: /tmp/bin/glab
    dest: /opt/local/bin/glab
    mode: a+x

- name: Install macports packages
  community.general.macports:
    name: "{{ item }}"
  loop: "{{ localhost_macports_packages }}"

- name: Install npm packages
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop: "{{ localhost_npm_packages }}"

- name: Upgrade macports packages
  community.general.macports:
    name: "{{ localhost_macports_packages }}"
    selfupdate: true
    upgrade: true
