---
- name: Install brew packages
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop: "{{ localhost_brew_packages }}"

- name: Instal brew casks
  community.general.homebrew:
    name: "homebrew/cask/{{ item }}"
    state: present
  loop: "{{ localhost_brew_casks }}"
