---
- name: Debug ansible_distribution
  ansible.builtin.debug:
    var: ansible_distribution
  tags:
    - install

- name: Install packages archlinux
  ansible.builtin.import_tasks: ./archlinux.yml
  become: true
  vars:
    state: present
    extra_args: ""
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - install

- name: Install packages mac
  ansible.builtin.import_tasks: ./mac.yml
  when:
    - ansible_distribution == "MacOSX"
  tags:
    - install

# - name: Configure
#   ansible.builtin.import_tasks: ./configure.yml
#   tags:
#     - configure
