---
- name: Debug ansible_distribution
  ansible.builtin.debug:
    var: ansible_distribution
  tags:
    - install
    - test

- name: Install packages for archlinux
  ansible.builtin.import_tasks: ./archlinux.yml
  become: true
  vars:
    state: present
    extra_args: ""
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - install
    - test

- name: Install packages for mac
  ansible.builtin.import_tasks: ./mac.yml
  become: true
  when:
    - ansible_distribution == "MacOSX"
  tags:
    - install
    - test

- name: Install node packages
  community.general.npm:
    global: true
    name: "{{ item }}"
  with_items: "{{ localhost_npm_packages }}"
  tags:
    - install
    - test

- name: Configure
  ansible.builtin.import_tasks: ./configure.yml
  tags:
    - install
    - test

- name: Install packages for archlinux
  ansible.builtin.import_tasks: ./archlinux.yml
  become: true
  vars:
    state: absent
    extra_args: "--recursive"
  when:
    - ansible_distribution == "Archlinux"
  tags:
    - test
