---
- name: Debug ansible_distribution
  ansible.builtin.debug:
    var: ansible_distribution
  tags:
    - install

- name: Install packages mac
  ansible.builtin.import_tasks: ./mac.yml
  when:
    - ansible_distribution == "MacOSX"
  tags:
    - install

- name: Pull config files
  ansible.builtin.import_tasks: ./pull.yml
  tags:
    - pull

- name: Push config files
  ansible.builtin.import_tasks: ./push.yml
  tags:
    - push
