---
- name: Debug ansible_distribution
  ansible.builtin.debug:
    var: ansible_distribution

- name: Install packages for archlinux
  ansible.builtin.import_tasks: ./archlinux.yml
  become: true
  when:
    - ansible_distribution == "Archlinux"

- name: Install packages for alpine
  ansible.builtin.import_tasks: ./alpine.yml
  become: true
  when:
    - ansible_distribution == "Alpine"

- name: Install packages for mac
  ansible.builtin.import_tasks: ./mac.yml
  become: true
  when:
    - ansible_distribution == "MacOSX"

- name: Setup i3
  ansible.builtin.import_tasks: ./i3.yml
  when:
    - ansible_distribution == "Alpine"

- name: Configure system
  ansible.builtin.import_tasks: ./configure.yml
  when:
    - ansible_distribution == "Alpine"
