---
- name: Debug ansible_distribution
  ansible.builtin.debug:
    var: ansible_distribution
  tags:
    - install

- name: Install packages mac
  ansible.builtin.import_tasks: ./mac.yml
  when:
    - ansible_distribution == "MacOSX"
  tags:
    - install

- name: Configure
  ansible.builtin.import_tasks: ./configure.yml
  tags:
    - pull
