---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  labels:
    app: openldap
spec:
  ports:
  - port: 1389
    name: openldap
  - port: 1636
    name: openldap-sec
  clusterIP: None
  selector:
    app: openldap
