---
# cluster.name: my-application
# node.name: node-1
# node.attr.rack: r1
path.data: /var/lib/elasticsearch
path.logs: /var/log/elasticsearch
# bootstrap.memory_lock: true
network.host: "{{elasticsearch_ip}}"
http.port: 9200
# action.destructive_requires_name: true
