---
xray_ssl_dir: /etc/ssl/xray
xray_ssl_cert_name: j.crt
xray_ssl_private_key_name: j.key
xray_config_dir: /usr/local/etc/xray

xray_server_config:
  inbounds:
    - port: 443
      protocol: vless
      settings:
        clients:
          - id: "{{ xray_client_0_id }}"
            level: 0
            email: "{{ xray_client_0_email }}"
          - id: "{{ xray_client_1_id }}"
            level: 0
            email: "{{ xray_client_1_email }}"
          - id: "{{ xray_client_2_id }}"
            level: 0
            email: "{{ xray_client_2_email }}"
        decryption: none
        fallbacks:
          - dest: 80
      streamSettings:
        network: tcp
        security: tls
        tlsSettings:
          serverName: "{{ xray_address }}"
          alpn:
            - http/1.1
          certificates:
            - certificateFile: "{{ xray_ssl_dir }}/{{ xray_ssl_cert_name }}"
              keyFile: "{{ xray_ssl_dir }}/{{ xray_ssl_private_key_name }}"
  outbounds:
    - protocol: freedom

xray_client_0_config:
  log:
    loglevel: warning
  outbounds:
    - protocol: vless
      settings:
        vnext:
          - address: "{{ xray_address }}"
            port: 443
            users:
              - id: "{{ xray_client_0_id }}"
                encryption: none
                level: 0
      streamSettings:
        network: tcp
        security: tls
        tlsSettings:
          allowInsecure: true
          serverName: "{{ xray_address }}"
          alpn:
            - h2
            - http/1.1
  inbounds:
    - port: 10800
      listen: 127.0.0.1
      protocol: socks
      settings:
        auth: noauth
        udp: true

xray_client_1_config:
  log:
    loglevel: warning
  outbounds:
    - protocol: vless
      settings:
        vnext:
          - address: "{{ xray_address }}"
            port: 443
            users:
              - id: "{{ xray_client_1_id }}"
                encryption: none
                level: 0
      streamSettings:
        network: tcp
        security: tls
        tlsSettings:
          allowInsecure: true
          serverName: "{{ xray_address }}"
          alpn:
            - h2
            - http/1.1
  inbounds:
    - port: 10800
      listen: 127.0.0.1
      protocol: socks
      settings:
        auth: noauth
        udp: true

xray_client_2_config:
  log:
    loglevel: warning
  outbounds:
    - protocol: vless
      settings:
        vnext:
          - address: "{{ xray_address }}"
            port: 443
            users:
              - id: "{{ xray_client_2_id }}"
                encryption: none
                level: 0
      streamSettings:
        network: tcp
        security: tls
        tlsSettings:
          allowInsecure: true
          serverName: "{{ xray_address }}"
          alpn:
            - h2
            - http/1.1
  inbounds:
    - port: 10800
      listen: 127.0.0.1
      protocol: socks
      settings:
        auth: noauth
        udp: true
