---
version: "3.6"
services:
  application:
    image: tarantool/tarantool:2
    container_name: tarantool
    command: tarantool /opt/tarantool/app/init.lua
    restart: always
    environment:
      TARANTOOL_USER_NAME: tarantool
      TARANTOOL_USER_PASSWORD: tarantool
    volumes:
      - ./init.lua:/opt/tarantool/app/init.lua
      - data:/var/lib/tarantool
    ports:
      - 3301:3301

volumes:
  data: null
