version: '3'
services:
  tarantool:
    image: tarantool/tarantool:2
    #build:
    #  dockerfile: ./Dockerfile
    #  context: .
    container_name: tarantool
    command: tarantool /opt/tarantool/app/init.lua
    restart: always
    environment:
      TARANTOOL_USER_NAME: tarantool
      TARANTOOL_USER_PASSWORD: tarantool
    volumes:
      - ./init.lua:/opt/tarantool/app/init.lua
      - ./validation.lua:/opt/tarantool/override/validation.lua
      - tarantool_data:/var/lib/tarantool
    ports:
      - 127.0.0.1:3301:3301
      - 127.0.0.1:8090:8090

  krakend:
    image: devopsfaith/krakend:2.4
    container_name: krakend
    restart: always
    volumes:
      - ./krakend.json:/etc/krakend/krakend.json
    ports:
      - 127.0.0.1:8082:8082
    #healthcheck:
    #  test: ["CMD-SHELL", "wget", "http://keycloak:8080"]
    #  interval: 5s
    #  timeout: 10s
    #  retries: 30
    #  start_period: 1s

  postgres:
    image: postgres:13.2-alpine
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
      PGPORT: 5455
    volumes:
      - postgres_data:/home/user/postgresql/data:Z
    ports:
      - 5455:5455
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "db_prod"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 1s

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.2
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5455/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8080
      HEALTHCHECK: "true"
    command: start-dev #--http-relative-path=/auth
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgres

  jaeger:
    image: jaegertracing/all-in-one:1.6
    container_name: jaeger
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 9411:9411 

volumes:
  postgres_data:
  tarantool_data:
