---
- hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Check krakend
      ansible.builtin.uri:
        url: http://localhost:8082

    - name: Check keycloak
      ansible.builtin.uri:
        url: http://localhost:8081
