---
- name: Install packages
  community.general.apk:
    name: "{{ item }}"
    update_cache: true
  loop:
    - gitea
    - postgresql14

- name: Push gitea configuration
  ansible.builtin.copy:
    src: ./roles/gitea/templates/app.ini
    dest: /etc/gitea/app.ini
    owner: gitea
    group: www-data
    mode: '0644'

- name: Start gitea service
  ansible.builtin.service:
    name: gitea
    state: started
    enabled: true
