---
- name: Disable registration (if needed)
  ansible.builtin.lineinfile:
    path: /var/lib/gitea/gitea/conf/app.ini
    regexp: '^DISABLE_REGISTRATION'
    line: "DISABLE_REGISTRATION = true"

# - name: Increase http post buffer size
#   ansible.builtin.lineinfile:
#     path: /var/lib/gitea/conf/app.ini
#     regexp: '^HTTP_POST_BUFFER_SIZE'
#     line: "HTTP_POST_BUFFER_SIZE = 50000000" # ~50MB

- name: Configure and deploy
  community.general.docker_container:
    name: "{{ gitea_container_name }}"
    image: "{{ gitea_image }}"
    state: started
    user:
    ports: "{{ gitea_ports }}"
    volumes: "{{ gitea_volumes }}"
    env: "{{ gitea_env }}"
    restart_policy: always
    restart: true
  tags:
    - deploy
