apiVersion: v2
appVersion: v0.1.21
description: A Helm chart for deploying krakend.io in Kubernetes provided and maintained
  by your friends at Equinix Metal
icon: https://www.krakend.io/images/logo-krakend.svg
name: krakend
type: application
version: v0.1.21
