---
# Source: template-job/templates/job.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: krakend-tests
spec:
  backoffLimit: 3
  activeDeadlineSeconds: 1800
  ttlSecondsAfterFinished: 180
  template:
    metadata:
    spec:
      imagePullSecrets:
        - name: docker-login
      containers:
        - name: krakend-tests
          image: "vnmntn/ansible"
          imagePullPolicy: IfNotPresent
          command: [sh]
          args:
            - -c
              #- apt update &&
              #  apt install ansible -y &&
              #  ansible-galaxy collection install ansible.posix &&
              #  ansible-galaxy collection install community.general &&
              #  echo "Container started..." &&
            - ansible-playbook /ansible/tests.yml
                -e krakend_url=http://krakend:80
                -e keycloak_url=http://keycloak:80
                -e keycloak_admin_username="admin"
                -e keycloak_admin_password="0qw0db3Dt6haYbyR"
          volumeMounts:
            - name: tests
              mountPath: /ansible
      volumes:
        - name: tests
          configMap:
            name: krakend-tests
      restartPolicy: Never
