---
version: '3.6'
services:
  web:
    image: 'gitlab/gitlab-ce:14.10.5-ce.0'
    restart: always
    hostname: 'gitlab.vnmntn.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.vnmntn.com'
        registry_external_url "https://gitlab-registry.vnmntn.com:6443"
    ports:
      - '8443:443'
      - '8022:22'
      - '6443:6443'
      # - '8080:80'
    volumes:
      - 'config:/etc/gitlab'
      - 'logs:/var/log/gitlab'
      - 'data:/var/opt/gitlab'
    shm_size: '256m'
volumes:
  config: null
  logs: null
  data: null
