---
pages:
  - id: 83
    title: Хосты и серверы теста
    description: information abount hosts with wireguard
    path: /srv/salt/haproxy/README.md

update_query: |
    mutation Page ($id: Int!, $title: String!, $description: String!, $content: String!) {
      pages {
        update (
            content: $content,
            description: $description,
            editor: "markdown", 
            isPublished: true, 
            isPrivate: false, 
            locale: "ru", 
            tags: [], 
            title: $title,
            id: $id
        ) {
          responseResult {
            succeeded,
            errorCode,
            slug,
            message
          },
          page {
            id,
            path,
            title
          }
        }
      }
    }
