---
- name: Iptables flush filter | IPTABLES
  ansible.builtin.iptables:
    chain: "{{ item }}"
    flush: true
  with_items:
    - INPUT
    - FORWARD
    - OUTPUT
  become: true

- name: Set the policy for the INPUT chain to DROP | IPTABLES
  ansible.builtin.iptables:
    chain: INPUT
    policy: DROP
  become: true

- name: Set the policy for the FORWARD chain to DROP | IPTABLES
  ansible.builtin.iptables:
    chain: FORWARD
    policy: DROP
  become: true

- name: Set the policy for the OUTPUT chain to ACCEPT | IPTABLES
  ansible.builtin.iptables:
    chain: OUTPUT
    policy: ACCEPT
  become: true

- name: Allow related and established connections | IPTABLES
  ansible.builtin.iptables:
    chain: INPUT
    ctstate: ESTABLISHED,RELATED
    jump: ACCEPT
  become: true

- name: Set the policy for the localhost to localhost | IPTABLES
  ansible.builtin.iptables:
    source: 127.0.0.1
    destination: 127.0.0.1
    chain: INPUT
    protocol: tcp
    jump: ACCEPT
  become: true

- name: Set the policy for the group SALT to ACCEPT | IPTABLES
  ansible.builtin.iptables:
    chain: INPUT
    protocol: tcp
    destination_ports:
      - "4505:4506"
    jump: ACCEPT
  become: true

- name: Set the policy for the group ICMP to ACCEPT | IPTABLES
  ansible.builtin.iptables:
    chain: INPUT
    protocol: icmp
    jump: ACCEPT
  become: true

- name: Save current state of the firewall in system file | IPTABLES
  community.general.iptables_state:
    state: saved
    path: /etc/iptables/iptables.rules
  become: true

- name: Enable and start iptables service | IPTABLES
  service:
    name: iptables
    state: restarted
    enabled: true
  become: true
