---
- name: Install requests | drone-runner
  ansible.builtin.pip:
    name: requests

- name: Container present | drone-runner
  community.docker.docker_container:
    name: drone-runner-docker-0
    state: started
    image: drone/drone-runner-docker:1
    restart_policy: always
    env:
      DRONE_RPC_PROTO: http
      DRONE_RPC_HOST: drone.vnmntn.com
      DRONE_RPC_SECRET: super-duper-secret
      DRONE_RUNNER_CAPACITY: '2'
      DRONE_RUNNER_NAME: drone-runner-docker-0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
