#!/bin/bash

# getopts
while getopts "c:w:a:" opt; do
    case $opt in
    c) COMMAND=$OPTARG ;;
    w) WS=$OPTARG ;;
    a) APP=$OPTARG ;;
    *) echo "No reasonable options found" ;;
    esac
done

# handle application
TILE_APP=$(xdotool search $APP)
if [[ "$?" -eq 0 ]]; then
    i3-msg workspace $WS
else
    i3-msg workspace $WS
    $COMMAND
fi