---
- name: Install docker python module | docker-clone
  ansible.builtin.pip:
    name:
      - docker

- name: Tag and push to private registry | docker-clone
  community.docker.docker_image:
    name: "{{ item.image }}:{{ item.tag }}"
    repository: "{{ registry }}/{{ item.image.split('/')[-1] }}"
    tag: "{{ item.tag }}"
    push: true
    source: pull
  with_items: "{{ images }}"
