---
- name: Install yum utils | DOCKER
  ansible.builtin.yum:
    name: yum-utils

- name: Add repo | DOCKER
  ansible.builtin.command: "yum-config-manager --add-repo {{ ci_docker_ce_url }}"
  register: myoutput
  changed_when: myoutput.rc != 0
  failed_when: myoutput.rc != 0

- name: Install packages | DOCKER
  ansible.builtin.yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: Setup service | DOCKER
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true
    daemon_reload: true
