---
- name: Install python requirements
  ansible.builtin.pip:
    name:
      - requests
      - docker

- name: Container present
  community.docker.docker_container:
    name: drone
    state: started
    restart: true
    image: drone/drone:2
    restart_policy: always
    published_ports:
      - 127.0.0.1:8443:443
      - 127.0.0.1:8080:80
    network_mode: host
    env:
      DRONE_GITEA_SERVER: https://git.vnmntn.com
      DRONE_GITEA_CLIENT_ID: "{{ GITEA_CLIENT_ID }}"
      DRONE_GITEA_CLIENT_SECRET: "{{ GITEA_CLIENT_SECRET }}"
      DRONE_RPC_SECRET: QACQyoiXKgQ8j7o8sdg
      DRONE_SERVER_HOST: drone.vnmntn.com
      DRONE_SERVER_PORT: "127.0.0.1:8080"
      DRONE_SERVER_PROTO: https
      DRONE_DATABASE_DRIVER: postgres
      DRONE_DATABASE_DATASOURCE: postgres://drone:drone@127.0.0.1:5432/drone?sslmode=disable
      DRONE_USER_CREATE: username:vnmntn,admin:true
    volumes:
      - /var/lib/drone:/data
  tags:
    - drone
