---
- name: Add helm repo | helm-clone
  command: "helm repo add {{ item.name }} {{ item.repo }}"
  with_items: "{{ charts }}"

- name: Update helm repo list | helm-clone
  command: helm repo update
  
- name: Pull helm repo | helm-clone
  command: "helm pull {{ item.name }}/{{ item.chart }} --version {{ item.version }} -d /tmp"
  with_items: "{{ charts }}"

- name: Push helm repo to a private helm chartmuseum | helm-clone
  command: "curl --user {{ CHARTMUSEUM_USERNAME }}:{{ CHARTMUSEUM_PASSWORD }} -X POST --upload-file /tmp/{{ item.chart }}-{{ item.version }}.tgz {{ chartmuseum }}"
  with_items: "{{ charts }}"