---
# tasks file for ci
- name: Clone helm charts
  ansible.builtin.import_tasks: ./helm-clone.yml

- name: Install docker
  ansible.builtin.import_tasks: ./docker.yml

- name: Install docker-compose
  ansible.builtin.import_tasks: ./docker-compose.yml

- name: Install kubectl
  ansible.builtin.import_tasks: ./kubectl.yml

- name: Install helm
  ansible.builtin.import_tasks: ./helm.yml

- name: Clone docker images
  ansible.builtin.import_tasks: ./docker-clone.yml