---
- name: Install fail2ban
  community.general.apk:
    name: fail2ban
    update_cache: true

# @task check fail2ban config path
- name: Copy fail2ban config
  ansible.builtin.copy:
    src: roles/fail2ban/files/jail.local
    dest: /etc/fail2ban/jail.local
    mode: '0640'

- name: Setup service
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted
    enabled: true
    daemon_reload: true
