---
groups:
  - name: Blackbox
    rules:
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Ошибка обнаружения домена {{ $labels.instance }}
          description: "метрика - `probe_success`"
          subscribers: "@alexmalder, @smiler25, @big_marshals"

      - alert: BlackboxSslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 7
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Истекает срок SSL-сертификата (instance {{ $labels.instance }})
          description: "SSL-сертификат истекает через {{ $value }} секунд\n  VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25, @Litigon"

      - alert: BlackboxSslCertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time() <= 0
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: SSL-сертификат истек (instance {{ $labels.instance }})
          description: "Необходимо обновить SSL-сертификат немедленно\n  VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25"

      - alert: BlackboxProbeIsLong
        expr: rate(probe_dns_lookup_time_seconds{}[1m]) > 1
        for: 0m
        labels:
          severity: critical
        annotations:
          summary: Время отклика домена (instance {{ $labels.instance }})
          description: "Увеличенное время отклика домена\n  VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25"
