---
groups:
  - name: Convert
    rules:
      - alert: Convert too slow
        expr: "sum(rate(combined_bucket[5m])) by (key) / sum(rate(combined_count[5m])) by (key) > 30 != Inf"
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Медленное конвертирование...
          description: "VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25"
