---
groups:
  - name: Cadvisor
    rules:
      - alert: Slicing is not available
        expr: absent(sum(container_cpu_usage_seconds_total{pod=~"slice-recog-server.*"})) == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Slicing is not available
          description: "VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25"

      - alert: Converter is not available
        expr: absent(sum(container_cpu_usage_seconds_total{pod=~"converter.*"})) == 1
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: Slicing is not available
          description: "VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25"
