---
groups:
  - name: Openldap
    rules:
      - alert: Openldap server has been failed
        expr: "rate(openldap_scrape{result='fail'}[1m]) > 0.1"
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Openldap server has been failed more 1 minutes...
          description: "VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25"
