---
groups:
  - name: Rabbitmq
    rules:
      - alert: Rabbitmq instance down
        expr: "absent(rabbitmq_up{} == 1)"
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Кролик упал или прямо сейчас упадёт! Нужно срочно идти поднимать!
          description: "VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25"

      - alert: Rabbitmq memory usage too agressive
        expr: "rabbitmq_node_mem_used > 10737418240"
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: Потребление памяти rabbitmq более 10GB суммарно!
          description: "VALUE = {{ $value }}"
          subscribers: "@alexmalder, @smiler25"
