---
groups:
  - name: Wireguard
    rules:
      - alert: Wireguard sent too large[experminal alert]
        expr: irate(wireguard_sent_bytes_total[30m]) > 1024 * 1024
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: VPN client sent too large (instance {{ $labels.instance }})
          description: "A wireguard client sent a many data\n  VALUE = {{ $value }}\n"
          subscribers: "@alexmalder, @smiler25"

      - alert: Wireguard received too large[experminal alert]
        expr: irate(wireguard_sent_bytes_total[30m]) > 1024 * 1024
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: VPN client receive too large (instance {{ $labels.instance }})
          description: "A wireguard client receive a many data\n  VALUE = {{ $value }}\n"
          subscribers: "@alexmalder, @smiler25"
