---
sources:
  my_source_id:
    type: docker_logs
    docker_host: http://localhost:2375

sinks:
  my_sink_id:
    type: elasticsearch
    inputs:
      - my_source_id
    endpoints: ['http://192.168.122.13:9200']
    mode: bulk
    compression: gzip
    api_version: v8
    bulk:
      action: create 
      index: "vector-messages-%Y-%m-%d"
