sudo mkdir /var/run/salt
sudo chown -R $USER:$USER /var/run/salt
xrdb -merge .Xresources
dbus-update-activation-environment --all

XDG_CONFIG_HOME=$HOME/.config polybar &
xfce4-power-manager &
setxkbmap -option ctrl:swapcaps &
xss-lock --transfer-sleep-lock -- i3lock --nofork &
gnome-keyring-daemon -r -d &
feh --bg-scale ~/.config/i3/purple-19.jpg &
syndaemon -i 1 &
picom --experimental-backend &

exec i3
