#!/bin/bash

#set -eo pipefail

glab issue list --page 1 --per-page 5

if [ "$?" -eq 0 ]; then
    echo "Get last 5 issues for checking glab"
else
    echo "Fatal error, stage 1"
fi

git add .

git commit -m "$1"

git push -u origin $(git rev-parse --abbrev-ref HEAD)

glab mr create -b $2 --description="created from glab cli" --title="$1"
