---
- name: Install common packages
  community.general.apk:
    name:
      - git
      - unzip
      - tar
      - ncdu
      - tmux
      - net-tools
      - htop
      - vim
      - wget
      - openssl
    update_cache: true

- name: Push network configuration
  ansible.builtin.template:
    src: roles/common/templates/interfaces
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'

- name: Restart networking service
  ansible.builtin.service:
    name: networking
    state: restarted

- name: Push apk repositories
  ansible.builtin.copy:
    src: roles/common/files/repositories
    dest: /etc/apk/repositories
    owner: root
    group: root
    mode: '0644'

- name: Install dev packages
  community.general.apk:
    name:
      - nnn
      - neovim
    update_cache: true
