---
- name: Install common packages
  community.general.apk:
    name:
      - git
      - unzip
      - tar
      - yum-utils
      - ncdu
      - tmux
      - net-tools
      - htop
      - vim
      - wget
      - nnn
      - openssl
      - neovim
