---
- name: "Register {{ package_name }} rpm package"
  stat:
    path: "/tmp/{{ package_name }}-{{ package_version }}.rpm"
  register: "package_rpm"

- name: "Push {{ package_name }} rpm package if does not exists"
  copy:
    src: "roles/elasticsearch/files/packages/{{ package_name }}-{{ package_version }}.rpm"
    dest: "/tmp/{{ package_name }}-{{ package_version }}.rpm"
    mode: '0640'
  when: "not package_rpm.stat.exists"

- name: Install rpm package
  command: "rpm -i /tmp/{{ package_name }}-{{ package_version }}.rpm"

#- name: "Install {{ package_name }} rpm package"
#  yum:
#    name: "/tmp/{{ package_name }}-{{ package_version }}.rpm"
#    state: "present"
