---
packages:
  base:
    - zsh
    - tmux
    - mc
    - ncdu
    - neovim
    - git
    - colordiff
    - net-tools
    - fzf
    - ripgrep
    - exa
    - tree
    - kitty
    - go
    - nnn
    - chromium
    - ansible
    - salt
    - flatpak
    - docker
    - npm
    - cpupower
    - pass
