---
packages:
  base:
    - zsh
    - tmux
    - mc
    - ncdu
    - neovim
    - git
    - colordiff
    - net-tools
    - fzf
    - ripgrep
    - exa
    - tree
    - kitty
    - nnn
    - docker
    - npm
    - cpupower
    - pass
    #- chromium
    #- salt
    #- flatpak
    #- go
  negwm:
    - xdo
    - tk
    - dash
  desktop:
    - dash
    - libtr
    - libtk
    - firefox
    - ttf-iosevka-nerd
    - unzip
    - ttf-iosevka-nerd
    - ttf-ubuntumono-nerd
    - tk
    - syndaemon
    - telegram-desktop
    - xdo
    - rofi
    - htop
    - virt-manager
    - go
    - obsidian
    - k9s
    - font-manager
