---
# defaults file for vector
vector_download_url: 'https://github.com/vectordotdev/vector/releases/download/v0.26.0'
vector_archive_name: 'vector-0.26.0-x86_64-unknown-linux-gnu.tar.gz'
vector_output_dir: 'vector-x86_64-unknown-linux-gnu'
