[[servers]]
host = "{{ ldap_vars.host }}"
port = {{ ldap_vars.port }}
use_ssl = {{ ldap_vars.use_ssl }}
start_tls = {{ ldap_vars.start_tls }}
ssl_skip_verify = {{ ldap_vars.ssl_skip_verify }}
bind_dn = "{{ ldap_vars.bind_dn }}"
bind_password = "{{ ldap_vars.bind_password }}"
search_filter = "{{ ldap_vars.search_filter }}"
search_base_dns = ["{{ ldap_vars.search_base_dns }}"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"
