---
global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - rules/blackbox.yml
  - rules/node_exporter.yml
  - rules/converter.yml
  - rules/openldap.yml
  - rules/ceph.yml
  - rules/rabbitmq.yml
  - rules/k8s.yml
  - rules/wireguard.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s
    static_configs:
      - targets: 
          - localhost:9090 
          - localhost:9115

  - job_name: 'federate'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="prometheus"}'
        - '{job="node_exporter"}'
        - '{job="docker"}'
    static_configs:
      - targets:
          - prometheus-test:9090

  - job_name: 'federate-k8s'
    scrape_interval: 15s
    honor_labels: true
    metrics_path: '/federate'
    params:
      'match[]':
        - '{job="kubelet"}'
        - '{APP_NAME="converter"}'
    static_configs:
      - targets:
          - kube-prometheus:9091

  - job_name: "bare-metal"
    static_configs:
      - targets:
          - bare-metal-node:9101

  - job_name: "ceph"
    static_configs:
      - targets:
          - ceph-node:9129

  - job_name: "node_exporter"
    static_configs:
      - targets:
          - virtual-machine:9100

  - job_name: blackbox_with_ssl
    metrics_path: /probe
    params:
      module: 
        - http_2xx_with_ssl
    static_configs:
      - targets:
          - https://domain-with-ssl.local
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: blackbox_without_ssl
    metrics_path: /probe
    params:
      module: 
        - http_2xx_without_ssl
    static_configs:
      - targets:
          - http://domain-without-ssl.local
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 127.0.0.1:9115

  - job_name: docker
    static_configs:
      - targets:
          - docker:8080

  - job_name: wireguard-server
    static_configs:
      - targets:
          - wireguard:9586

  - job_name: rabbitmq
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets:
          - rabbitmq:9419

  - job_name: mysql
    scrape_interval: 20s
    scrape_timeout: 20s
    static_configs:
      - targets:
          - mysql:9104

  - job_name: openldap
    static_configs:
      - targets:
          - openldap:9330

  - job_name: redpanda
    static_configs:
      - targets:
          - redpanda1:9644
          - redpanda2:9644
          - redpanda3:9644

  - job_name: redpanda_public
    static_configs:
      - targets:
          - redpanda1:9644
          - redpanda2:9644
          - redpanda3:9644
    metrics_path: /public_metrics
