{{ if .Values.serviceMonitor.enabled -}}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "tarantool.fullname" . }}
  labels: {{- include "tarantool.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{- range $key, $value := .Values.serviceMonitor.annotations }}
    {{ $key }}: {{ tpl $value $ | quote }}
    {{- end }}
  {{- end }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels: {{- include "tarantool.selectorLabels" . | nindent 6 }}
  endpoints:
    - interval: {{ .Values.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      path: /metrics
      targetPort: {{ .Values.serviceMonitor.targetPort }}
{{- end }}
