---
# tasks file for postgres

#- name: Install postgresql centos/almalinux
#  ansible.builtin.dnf:
#    name: '@postgresql:12'
#    state: present

- name: Install postgresql fedora
  ansible.builtin.dnf:
    name:
      - postgresql-server
      - postgresql-contrib
    state: present

- name: Find out if PostgreSQL is initialized
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: Initialize PostgreSQL
  ansible.builtin.command: "postgresql-setup initdb"
  register: postgres_init
  changed_when: postgres_init.rc == 0
  failed_when: postgres_init.rc != 0
  when: not postgres_data.stat.exists

- name: Setup pg hba
  ansible.builtin.template:
    src: "roles/postgres/files/pg_hba.conf"
    dest: "~/data/pg_hba.conf"
    owner: postgres
    mode: '0600'
  become: true
  become_user: postgres

- name: Setup service
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true
    daemon_reload: true

- name: Install Python packages
  ansible.builtin.yum:
    name: python3-psycopg2
    state: present

- name: Create database
  community.postgresql.postgresql_db:
    state: present
    name: "{{ item.database }}"
  with_items: "{{ hostvars['POSTGRES']['config']['users'] }}"
  become: true
  become_user: postgres

- name: Create database user
  community.postgresql.postgresql_user:
    state: present
    name: "{{ item.user }}"
    password: "{{ item.password }}"
  with_items: "{{ hostvars['POSTGRES']['config']['users'] }}"
  become: true
  become_user: postgres

- name: Grant database user access to database
  community.postgresql.postgresql_privs:
    type: database
    database: "{{ item.database }}"
    roles: "{{ item.user }}"
    grant_option: false
    privs: all
  with_items: "{{ hostvars['POSTGRES']['config']['users'] }}"
  become: true
  become_user: postgres

- name: Setup listen addresses
  ansible.builtin.replace:
    path: "~/data/postgresql.conf"
    regexp: '.*listen_add.*'
    replace: "listen_addresses = '{{ hostvars['POSTGRES']['config']['listen_addresses'] }}'"
  become: true
  become_user: postgres

- name: Setup log log_directory
  ansible.builtin.replace:
    path: "~/data/postgresql.conf"
    regexp: '.*log_directory.*'
    replace: "log_directory = '/var/log'"
  become: true
  become_user: postgres

- name: Setup log filename
  ansible.builtin.replace:
    path: "~/data/postgresql.conf"
    regexp: '.*log_filename.*'
    replace: "log_filename = 'postgresql.log'"
  become: true
  become_user: postgres

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    state: touch
    path: /var/log/postgresql.log
    owner: postgres
    group: postgres
    mode: '0644'

- name: Push service
  ansible.builtin.copy:
    src: "roles/postgres/files/postgres.service"
    dest: "/usr/lib/systemd/system/postgresql.service"
    owner: root
    group: root
    mode: 0644

- name: Setup service
  ansible.builtin.systemd:
    name: postgresql
    state: restarted
    enabled: true
    daemon_reload: true
