---
- hosts: vm
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux: 
        state: disabled

    - name: remove ugly packages
      yum:
        name: 
          - firewalld
        state: absent
