---
- hosts: vm
  tasks:
    - name: Disable SELinux
      ansible.posix.selinux: 
        state: disabled

    - name: remove ugly packages
      yum:
        name: 
          - firewalld
        state: absent

    - name: install epel release
      yum:
        name: epel-release

    - name: install admin tools
      yum:
        name:
          - git
          - unzip
          - tar
          - yum-utils
          - ncdu
          - tmux
          - net-tools
          - htop
          - vim
