---
- hosts: gitlab-runner
  vars:
    DOCKER_CE: 'https://download.docker.com/linux/centos/docker-ce.repo'

  tasks:
    - name: install yum utils
      yum:
        name: yum-utils

    - name: add docker repo
      command: "yum-config-manager --add-repo {{ DOCKER_CE }}"

    - name: install docker packages
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: enable and start docker
      systemd:
        name: docker
        state: restarted
        enabled: yes
        daemon_reload: yes
