---
# @tags: 
# - ci
- name: Install docker
  hosts: drone-runner
  vars:
    docker_ce: 'https://download.docker.com/linux/centos/docker-ce.repo'

  tasks:
    - name: Install yum utils
      ansible.builtin.yum:
        name: yum-utils

    - name: Add repo
      ansible.builtin.command: "yum-config-manager --add-repo {{ docker_ce }}"
      register: myoutput
      changed_when: myoutput.rc != 0
      failed_when: myoutput.rc != 0

    - name: Install packages
      ansible.builtin.yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Setup service
      ansible.builtin.systemd:
        name: docker
        state: restarted
        enabled: true
        daemon_reload: true
