---
- name: Pull from public and push to private registry
  hosts: gr-test
  vars:
    registry: cr.yandex/crpqd3tp73le5j7colpa/devops
    images:
      - docker.io/bitnami/kafka:3.1.1-debian-10-r6
      - docker.io/bitnami/nginx:1.22.0-debian-11-r3
      - docker.io/bitnami/postgresql:15.3.0-debian-11-r0
      - docker.io/bitnami/redis:6.2.7-debian-11-r3
      - docker.io/bitnami/zookeeper:3.8.0-debian-10-r0
      - docker.io/bitnami/zookeeper:3.8.0-debian-10-r63
      - getsentry/relay:23.5.0
      - getsentry/sentry:23.5.0
      - getsentry/snuba:23.5.0
      - ghcr.io/external-secrets/external-secrets:v0.8.0
      - postgres:13
      - quay.io/jcmoraisjr/haproxy-ingress:v0.14.2
      - quay.io/jetstack/cert-manager-acmesolver:v1.6.1
      - quay.io/jetstack/cert-manager-cainjector:v1.6.1
      - quay.io/jetstack/cert-manager-controller:v1.6.1
      - quay.io/jetstack/cert-manager-webhook:v1.6.1
      - quay.io/k8scsi/csi-attacher:v3.0.1
      - quay.io/k8scsi/csi-node-driver-registrar:v1.2.0
      - quay.io/k8scsi/csi-provisioner:v2.1.0
      - quay.io/prometheus-operator/prometheus-config-reloader:v0.62.0
      - quay.io/prometheus-operator/prometheus-operator:v0.62.0
      - quay.io/prometheus/alertmanager:v0.25.0
      - quay.io/prometheus/node-exporter:v1.5.0
      - quay.io/prometheus/prometheus:v2.41.0
      - quay.io/prometheuscommunity/postgres-exporter:v0.11.1
      - registry.k8s.io/ingress-nginx/controller:v1.4.0@sha256:34ee929b111ffc7aa426ffd409af44da48e5a0eea1eb2207994d9e0c0882d143
      - registry.k8s.io/kube-state-metrics/kube-state-metrics:v2.7.0
      - whereisaaron/kube-syslog-sidecar:latest
      - yandex/clickhouse-server:20.12.8.5

  tasks:
    - name: Install docker python module | docker-clone
      ansible.builtin.pip:
        name:
          - docker

    - name: Tag and push to private registry | docker-clone
      community.docker.docker_image:
        name: "{{ item.split(':')[0] }}:{{ item.split(':')[1] }}"
        repository: "{{ registry }}/{{ item.split(':')[0].split('/')[-1] }}"
        tag: "{{ item.split(':')[1] }}"
        push: true
        source: pull
      with_items: "{{ images }}"
