---
- name: Pull from public and push to private registry
  hosts: cloud0
  vars:
    registry: git.vnmntn.com/alexmalder
    images:
      - getsentry/sentry:23.5.0
      - getsentry/relay:23.5.0
      - getsentry/snuba:23.5.0
      - bitnami/redis:6.2.7-debian-11-r3
      - yandex/clickhouse-server:20.12.8.5
      - bitnami/postgresql:15.3.0-debian-11-r0
      - bitnami/zookeeper:3.8.0-debian-10-r0
      - bitnami/zookeeper:3.8.0-debian-10-r63
      - bitnami/kafka:3.1.1-debian-10-r6
      - danielqsj/kafka-exporter:v1.6.0
  tasks:
    - name: Install docker python module | docker-clone
      ansible.builtin.pip:
        name:
          - docker

    - name: Tag and push to private registry | docker-clone
      community.docker.docker_image:
        name: "{{ item.split(':')[0] }}:{{ item.split(':')[1] }}"
        repository: "{{ registry }}/{{ item.split(':')[0].split('/')[-1] }}"
        tag: "{{ item.split(':')[1] }}"
        push: true
        source: pull
      with_items: "{{ images }}"
