---
- name: Run playbook locally for git mirror
  hosts: 127.0.0.1
  connection: local
  vars:
    dest_url: https://github.com/alexmalder
  tasks:
    - name: Get list of repos
      ansible.builtin.uri:
        url: "https://{{ GIT_URL }}/api/v4/projects"
        method: GET
        status_code:
          - 200
        return_content: true
        body_format: json
        headers:
          Content-Type: application/json
          PRIVATE-TOKEN: "{{ PRIVATE_TOKEN }}"
        validate_certs: false
      register: result

    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: "/tmp/{{ item.name }}"
      with_items: "{{ result.json }}"

    - name: Clone repositories into workdir
      ansible.builtin.git:
        repo: "{{ item.web_url }}"
        dest: "/tmp/{{ item.name }}"
        version: master
        single_branch: true
        force: true
        #version: "{{ item.default_branch }}"
      with_items: "{{ result.json }}"
      # no_log: true

    - name: Remote add
      ansible.builtin.command: "git -C /tmp/{{ item.name }} remote add dest {{ dest_url }}/{{ item.name }}"
      with_items: "{{ result.json }}"

    - name: Push
      ansible.builtin.command: "git -C /tmp/{{ item.name }} push -u dest master"
      with_items: "{{ result.json }}"
