---
- hosts: 127.0.0.1
  connection: local
  vars:
    src_url: https://gitlab.vnmntn.com/alexmalder
    dest_url: https://github.com/alexmalder
    dest_remote: dest
    repos:
      - ansible
      - obsidian
      - reader
      - scraper
      - store
      - template
      - vault
  tasks:
    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: "/tmp/{{ item }}"
      with_items: "{{ repos }}"

    - name: Clone repositories into /tmp
      ansible.builtin.git:
        repo: "{{ src_url }}/{{ item }}"
        dest: "/tmp/{{ item }}"
        single_branch: true
        force: true
        version: master
      with_items: "{{ repos }}"

    - name: Git remote add
      ansible.builtin.command: "git -C /tmp/{{ item }} remote add {{ dest_remote }} {{ dest_url }}/{{ item }}"
      with_items: "{{ repos }}"

    - name: Git push
      ansible.builtin.command: "git -C /tmp/{{ item }} push -u dest master"
      with_items: "{{ repos }}"
