---
- name: Make and pull gitea backup
  hosts: cloud0
  vars:
    ansible_user: git
  tasks:
#    - name: Remove default appiconset
#      file: 
#        path: "{{ ansible_env.HOME }}/backups"
#        state: absent

    - name: Create backup directory
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/backups"
        state: directory
        mode: '0755'
        owner: git
        group: git

    - name: Make gitea backup
      command: 
        cmd: "gitea dump -c /etc/gitea/app.ini"
        chdir: "{{ ansible_env.HOME }}/backups"

    - name: Recursively find backups
      ansible.builtin.find:
        paths: "{{ ansible_env.HOME }}/backups"
        recurse: yes
      register: backups

    - name: Store file into backups local directory
      ansible.builtin.fetch:
        src: "{{ item.path }}"
        dest: "~/Documents/backups"
      loop: "{{ backups.files }}"
