---
- name: Install gitlab runner
  hosts: gitlab-runner
  vars:
    gitlab_runner_script_url: 'https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh'

  tasks:
    - name: Download installation script
      ansible.builtin.get_url:
        url: "{{ gitlab_runner_script_url }}"
        dest: /tmp/script.rpm.sh
        mode: 'a+x'

    - name: Execute gitlab-runner setup script
      ansible.builtin.command: /tmp/script.rpm.sh
      register: myoutput
      changed_when: myoutput.rc != 0
      failed_when: myoutput.rc != 0

    - name: Install gitlab runner
      ansible.builtin.yum:
        name: gitlab-runner
