---
- hosts: gitlab-runner
  vars:
    gitlab_runner_script_url: 'https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh'

  tasks:
    - name: Download foo.conf
      get_url:
        url: "{{ gitlab_runner_script_url }}"
        dest: /tmp/script.rpm.sh
        mode: 'a+x'

    - name: Execute gitlab-runner setup script
      command: /tmp/script.rpm.sh

    - name: Install gitlab runner
      yum:
        name: gitlab-runner
