---
# @tags: 
# - ci
- name: Install helm with script
  hosts: drone-runner
  vars:
    helm_installation_script: 'https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3'

  tasks:
    - name: Download helm installation script
      ansible.builtin.get_url:
        url: "{{ helm_installation_script }}"
        dest: /tmp/get-helm.sh
        mode: 'a+x'

    - name: Execute helm installation script
      ansible.builtin.command: bash /tmp/get-helm.sh
      register: myoutput
      changed_when: myoutput.rc != 0
      failed_when: myoutput.rc != 0
