---
- name: Run keycloak in docker with docker-compose
  hosts: cloud0
  gather_facts: false
  vars:
    ansible_python_interpreter: /usr/bin/python3.8
  tasks:
    - name: Execute docker-compose
      community.docker.docker_compose:
        project_name: openldap
        definition:
          version: '3.7'
          services:
            keycloak:
              image: quay.io/keycloak/keycloak:legacy
              container_name: keycloak
              network_mode: host
              environment:
                DB_VENDOR: POSTGRES
                DB_ADDR: 127.0.0.1
                DB_DATABASE: keycloak
                DB_USER: keycloak
                DB_SCHEMA: public
                DB_PASSWORD: keycloak
                KEYCLOAK_USER: admin
                KEYCLOAK_PASSWORD: Pa55w0rd
                KEYCLOAK_HOSTNAME: keycloak.vnmntn.com
                PROXY_ADDRESS_FORWARDING: 'true'
                #JDBC_PARAMS: "ssl=true"
              #ports:
              #- 8080:8080
      register: output

    - name: Print debug info
      ansible.builtin.debug:
        var: output
