---
- name: Install libvirtd on archlinux
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Install packages
      become: true
      community.general.pacman:
        name:
          - libvirt
          - virt-manager
          - ebtables
          - dnsmasq
          - dmidecode
          - qemu-desktop
        state: present

    - name: Enable and start libvirtd
      become: true
      ansible.builtin.systemd:
        name: libvirtd
        enabled: true
        daemon_reload: true
        state: started
