---
- hosts: selectel
  tasks:
    - name: Remove the 'firewalld' package
      ansible.builtin.yum:
        name: firewalld
        state: absent

    - name: Install the 'Virtualization Host' package group
      ansible.builtin.dnf:
        name: '@Virtualization Host'
        state: present

    - name: Enable and start libvirtd
      ansible.builtin.systemd:
        name: libvirtd
        state: started
        enabled: yes
        daemon_reload: no

    - name: Download 'centos 8 stream' boot image
      get_url:
        url: http://mirror.truenetwork.ru/centos/8-stream/isos/x86_64/CentOS-Stream-8-x86_64-20221125-boot.iso
        dest: /var/lib/libvirt/images/CentOS-Stream-8-x86_64-20221125-boot.iso
        mode: '0660'
