---
- name: Include variables
  gather_facts: false
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: Register variable
      ansible.builtin.command: "pass show ansible/openldap/ldap-admin-password"
      register: ldap_admin_password_raw
      changed_when: ldap_admin_password_raw.rc == 0
      failed_when: ldap_admin_password_raw.rc != 0

    - name: Add host variable
      ansible.builtin.add_host:
        name: LDAP
        ldap_admin_password: "{{ ldap_admin_password_raw.stdout }}"

- name: Run openldap in docker with docker-compose
  hosts: cloud0
  gather_facts: false
  vars:
    bind_ip: 0.0.0.0
    base_dn: "dc=vnmntn,dc=com"
  tasks:
    - name: Execute docker-compose
      community.docker.docker_compose:
        project_name: openldap
        definition:
          version: '3.7'
          services:
            openldap:
              image: bitnami/openldap:2.6
              restart: always
              ports:
                - '{{ bind_ip }}:1389:1389'
                - '{{ bind_ip }}:1636:1636'
              environment:
                - LDAP_ADMIN_USERNAME=admin
                - LDAP_ADMIN_PASSWORD={{ hostvars['LDAP']['ldap_admin_password'] }}
                - LDAP_ROOT={{ base_dn }}
                #- LDAP_USERS=user01,user02
                #- LDAP_PASSWORDS=password1,password2
              volumes:
                - 'openldap:/bitnami/openldap'
            lam:
              image: ldapaccountmanager/lam:stable
              restart: always
              ports:
                - '{{ bind_ip }}:8090:80'
              environment:
                # skip LAM preconfiguration (lam.conf + config.cfg), values: (true/false)
                # If set to true the other variables below have no effect.
                - LAM_SKIP_PRECONFIGURE=false
                # domain of LDAP database root entry, will be converted to dc=...,dc=...
                - LDAP_DOMAIN=vnmntn.com
                # LDAP base DN to overwrite value generated by LDAP_DOMAIN
                - LDAP_BASE_DN={{ base_dn }}
                # LDAP users DN to overwrite value provided by LDAP_BASE_DN
                - LDAP_USERS_DN=ou=users,{{ base_dn }}
                # LDAP groups DN to overwrite value provided by LDAP_BASE_DN
                - LDAP_GROUPS_DN=ou=groups,{{ base_dn }}
                # LDAP server URL
                - LDAP_SERVER=ldap://openldap:1389
                # LDAP admin user (set as login user for LAM)
                - LDAP_USER=cn=admin,{{ base_dn }}
                # default language, e.g. en_US, de_DE, fr_FR, ...
                - LAM_LANG=en_US
                # LAM configuration master password and password for server profile "lam"
                - LAM_PASSWORD=lam
                # configuration database (files or mysql)
                - LAM_CONFIGURATION_DATABASE=files
                # LAM Pro license (line breaks can be removed)
                # - LAM_LICENSE=
                # deactivate TLS certificate checks, activate for development only
                - LAM_DISABLE_TLS_CHECK=true
                # LDAP organisation name for OpenLDAP
                - LDAP_ORGANISATION="LDAP"
                # LDAP admin password
                - LDAP_ADMIN_PASSWORD=adminpassword
                # password for LDAP read-only user
                - LDAP_READONLY_USER_PASSWORD=readonlypw

          volumes:
            openldap:
      register: output
      vars:
        ansible_python_interpreter: /usr/bin/python3.8

    - name: Print debug info
      ansible.builtin.debug:
        var: output
