---
- name: Run openldap in docker with docker-compose
  hosts: cloud0
  gather_facts: false
  vars:
    bind_ip: 0.0.0.0
    base_dn: "dc=vnmntn,dc=ru"
    domain: "vnmntn.ru"
  tasks:
    - name: Create a volume for openldap server
      community.docker.docker_volume:
        name: openldap

    - name: Run openldap server
      community.docker.docker_container:
        name: openldap
        image: bitnami/openldap:2.6
        restart_policy: always
        recreate: true
        state: started
        env:
          LDAP_ADMIN_USERNAME: "admin"
          LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
          LDAP_ROOT: "{{ base_dn }}"
          LDAP_USERS: "user01,user02"
          LDAP_PASSWORDS: "password1,password2"
        network_mode: host
        volumes:
          - openldap:/bitnami/openldap

    - name: Run ldap account manager user interface
      community.docker.docker_container:
        name: lam
        image: ldapaccountmanager/lam:stable
        restart_policy: always
        recreate: true
        state: started
        network_mode: host
        env:
          LAM_SKIP_PRECONFIGURE: "false"
          LDAP_DOMAIN: "{{ domain }}"
          LDAP_BASE_DN: "{{ base_dn }}"
          LDAP_USERS_DN: "ou=users,{{ base_dn }}"
          LDAP_GROUPS_DN: "ou=groups,{{ base_dn }}"
          LDAP_SERVER: "ldap://127.0.0.1:1389"
          LDAP_USER: "cn=admin,{{ base_dn }}"
          LAM_LANG: en_US
          LAM_PASSWORD: lam
          LAM_CONFIGURATION_DATABASE: files
          LAM_DISABLE_TLS_CHECK: "true"
          LDAP_ORGANISATION: "LDAP"
          LDAP_ADMIN_PASSWORD: "{{ ldap_admin_password }}"
          LDAP_READONLY_USER_PASSWORD: "readonlypw"
