---
- hosts: 127.0.0.1
  connection: local
  vars:
    images:
    - image: docker.io/bitnami/memcached
      tag: 1.6.9-debian-10-r114
    - image: docker.io/bitnami/postgresql
      tag: 11.11.0-debian-10-r62
    - image: docker.io/drone/drone
      tag: 2.12.1
    - image: docker.io/library/nginx
      tag: 1.23.2-alpine
    - image: drone/drone-runner-kube
      tag: 1.0.0-rc.3
    - image: gitea/gitea
      tag: 1.17.3
    - image: grafana/grafana
      tag: 9.3.1
    - image: quay.io/calico/kube-controllers
      tag: v3.23.3
    - image: quay.io/calico/node
      tag: v3.23.3
    - image: quay.io/kiwigrid/k8s-sidecar
      tag: 1.21.0
    - image: quay.io/prometheus-operator/prometheus-config-reloader
      tag: v0.61.1
    - image: quay.io/prometheus-operator/prometheus-operator
      tag: v0.61.1
    - image: quay.io/prometheus/alertmanager
      tag: v0.24.0
    - image: quay.io/prometheus/node-exporter
      tag: v1.5.0
    - image: quay.io/prometheus/prometheus
      tag: v2.40.5
    - image: bitnami/openldap
      tag: 2.6
    - image: ldapaccountmanager/lam
      tag: stable
  tasks:
    - name: Archive image
      community.docker.docker_image:
        name: "{{ item.image }}"
        tag: "{{ item.tag }}"
        archive_path: "/data/images/{{ item.image | replace('/', '-') }}-{{ item.tag }}.tar"
        source: pull
      with_items: "{{ images }}"
