---
- name: Get files
  ansible.builtin.find:
    paths: "{{ base_src }}/{{ diff_path }}"
    recurse: true
    hidden: true
  register: result

- name: Diff files
  ansible.builtin.command: 'diff {{ item.path }} $HOME/.config/{{ item.path.replace("roles/localhost/files/.config/", "") }}'
  register: diff_result
  changed_when: diff_result.rc == 0
  failed_when: diff_result.rc != 0
  with_items: "{{ result.files }}"
