---
- name: Install bind
  yum:
    name:
      - bind
      - bind-utils

- name: Push named configuration
  copy:
    src: "roles/bind/files/named.conf"
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640

- name: Push db configuration
  copy:
    src: "roles/bind/files/vnmntn.pro.db"
    dest: "/var/named/vnmntn.pro.db"
    owner: named
    group: named
    mode: 0660

- name: Push rev configuration
  copy:
    src: "roles/bind/files/vnmntn.pro.rev"
    dest: "/var/named/vnmntn.pro.rev"
    owner: named
    group: named
    mode: 0660

- name: Check db configuration
  command: named-checkzone vnmntn.pro /var/named/vnmntn.pro.db

- name: Check rev configuration
  command: named-checkzone 192.168.122.16 /var/named/vnmntn.pro.rev

- name: Enable and restart named service
  systemd:
    name: named
    state: restarted
    enabled: yes
    daemon_reload: yes
