---
- name: Install bind
  ansible.builtin.yum:
    name:
      - bind
      - bind-utils

- name: Push named configuration
  ansible.builtin.copy:
    src: "roles/bind/files/named.conf"
    dest: /etc/named.conf
    owner: root
    group: named
    mode: 0640

- name: Push db configuration
  ansible.builtin.copy:
    src: "roles/bind/files/vnmntn.pro.db"
    dest: "/var/named/vnmntn.pro.db"
    owner: named
    group: named
    mode: 0660

- name: Push rev configuration
  ansible.builtin.copy:
    src: "roles/bind/files/vnmntn.pro.rev"
    dest: "/var/named/vnmntn.pro.rev"
    owner: named
    group: named
    mode: 0660

- name: Enable and restart named service
  ansible.builtin.systemd:
    name: named
    state: restarted
    enabled: true
    daemon_reload: true
