---
- name: Install bind
  ansible.builtin.yum:
    name:
      - bind
      - bind-utils

- name: Push named configuration
  ansible.builtin.template:
    src: "roles/bind/files/named.conf.jinja"
    dest: /etc/named.conf
    owner: root
    group: named
    mode: '0640'

- name: Push db configuration
  ansible.builtin.template:
    src: "roles/bind/files/{{ domain }}.db"
    dest: "/var/named/{{ domain }}.db"
    owner: named
    group: named
    mode: '0660'

- name: Push rev configuration
  ansible.builtin.template:
    src: "roles/bind/files/{{ domain }}.rev"
    dest: "/var/named/{{ domain }}.rev"
    owner: named
    group: named
    mode: '0660'

- name: Enable and restart named service
  ansible.builtin.systemd:
    name: named
    state: restarted
    enabled: true
    daemon_reload: true
