---
- name: Install base ALPINE packages | PACKAGES
  become: true
  community.general.apk:
    name: "{{ packages.base }}"

- name: Install dev ALPINE packages | PACKAGES
  become: true
  community.general.apk:
    name:
      - font-iosevka
      - font-iosevka-nerd
      - font-manager
      - wl-clipboard
      - virt-manager
      - salt-ssh
      - salt-master
      - bluez
      - alsa-utils
      - alsa-utils-doc
      - alsa-lib
      - alsaconf
      - alsa-ucm-conf
      - task
      - libvirt
      - libvirt-qemu
      - libvirt-daemon
      - qemu-img
      - qemu-system-x86_64
      - qemu-modules
      - openrc
      - ffmpeg
      - mpv
      - util-linux
      - bind-tools
    state: present
