---
- name: Install base archlinux packages
  become: true
  community.general.pacman:
    name:
      - zsh
      - tmux
      - mc
      - ncdu
      - neovim
      - git
      - colordiff
      - net-tools
      - fzf
      - ripgrep
      - exa
      - tree
      - kitty
      - nnn
      - docker
      - npm
      - cpupower
      - pass
      - unzip

- name: Install dev archlinux packages
  become: true
  community.general.pacman:
    name:
      - python-pip
      - polybar
      - wireguard-tools
      - make
      - cmake
      - llvm
      - clang
      - glab
      - kubectl
      - helm
      - gopls
      - dash
      - bottom
      - htop
      - virt-manager
      - go
      - k9s
      - font-manager
      - docker-compose
      # negwm
      - tk
      - dash
      - xdo

- name: Install graphic packages
  become: true
  community.general.pacman:
    name:
      - xorg
      - xorg-server
      - xorg-xinit
      - i3-gaps
      - dmenu
      - qutebrowser
      - telegram-desktop
      - evolution
      - xfce4-power-manager
      - nautilus
      - alacritty
      - xdotool
      - rofi
      - gnome-keyring
      - xclip
      - qtcreator
      - deepin-screenshot
      - dunst
      - obsidian
      - feh
      - firefox
      - xf86-input-synaptics
      - picom
      - lxappearance
      # fonts
      - fontconfig
      - ttf-iosevka-nerd
      - ttf-ubuntumono-nerd

- name: Install node packages
  become: true
  community.general.npm:
    global: true
    name: "{{ item }}"
  with_items:
      - pyright
      - pm2
      - bash-language-server
      - yaml-language-server
