---
- name: install zi to .config
  git:
    repo: "https://github.com/z-shell/zi"
    dest: "~/.config/zi"
    version: main

- name: Deploy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - src: "roles/{{ role_name }}/files/.config"
      dest: "~/"
    - src: "roles/{{ role_name }}/files/.zshrc"
      dest: "~/"
    - src: "roles/{{ role_name }}/files/.zsh"
      dest: "~/"
    - src: "roles/{{ role_name }}/files/.clang-format"
      dest: "~/"
    - src: "roles/{{ role_name }}/files/.tmux.conf"
      dest: "~/"
    - src: "roles/{{ role_name }}/files/.xinitrc"
      dest: "~/"
    - src: "roles/{{ role_name }}/files/.Xresources"
      dest: "~/"

- name: Deploy sound configuration file to modprobe for alpine
  become: true
  copy:
    src: "roles/{{ role_name }}/files/etc/modprobe.d/alsa-alpine.conf"
    dest: /etc/modprobe.d/alsa.conf
  when:
    - ansible_distribution == "Alpine"

- name: Deploy sound configuration file to modprobe for archlinux
  become: true
  copy:
    src: "roles/{{ role_name }}/files/etc/modprobe.d/alsa-archlinux.conf"
    dest: /etc/modprobe.d/alsa.conf
  when:
    - ansible_distribution == "Archlinux"

- name: Setup i3 by template
  template:
    src: "roles/{{ role_name }}/templates/i3.jinja"
    dest: ~/.config/i3/config

- name: Restart i3 if needed
  command: i3-msg restart
  when:
    - ansible_distribution == "Archlinux"
