---
- name: Install flatpak
  apk:
    name: flatpak

- name: Setup flatpak default repository
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Install flatpak packages | PACKAGES
  community.general.flatpak:
    name:
      - com.dec05eba.gpu_screen_recorder 
      - com.mattjakeman.ExtensionManager
      - com.visualstudio.code        
      - io.dbeaver.DBeaverCommunity 
      - io.github.kotatogram                      
      - io.podman_desktop.PodmanDesktop           
      - md.obsidian.Obsidian                      
      - org.mozilla.firefox                       
      - us.zoom.Zoom 
