---
# tasks file for init
- name: Install packages for archlinux | PACKAGES
  import_tasks: ./archlinux.yml
  when:
    - ansible_distribution == "Archlinux"

- name: Install packages for alpine | PACKAGES
  import_tasks: ./alpine.yml
  when:
    - ansible_distribution == "Alpine"    

- name: Install flatpak packages | PACKAGES
  import_tasks: ./flatpak.yml
  when:
    - ansible_distribution == "Alpine"    
