---
# tasks file for wireguard
- name: Install epel and el
  ansible.builtin.dnf:
    name:
      - epel-release
      - elrepo-release

- name: Install wireguard
  ansible.builtin.dnf:
    name:
      - kmod-wireguard
      - wireguard-tools

- name: Generate server config file
  ansible.builtin.template:
    src: "roles/wireguard/templates/server.conf"
    dest: "/etc/wireguard/wg0.conf"
    mode: 0640
  become: true

- name: Enable and restart wireguard service
  ansible.builtin.systemd:
    name: wg-quick@wg0
    state: reloaded
    enabled: true
    daemon_reload: true
