---
- name: Push sshd configuration
  ansible.builtin.copy:
    src: ./roles/sshd/files/sshd_config
    dest: /etc/ssh/sshd_config
    owner: sshd
    group: sshd
    mode: '0640'

- name: Enable and restart sshd service
  service:
    name: sshd
    state: restarted
    enabled: true
