name: ci

on:
  push:
    branches:
      - master

jobs:
  test-ansible:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Prepare env
        run: sudo apt install ansible -y

      - name: Docker build
        run: docker build . -t ansible

      #- name: Login to Docker Hub
      #  uses: docker/login-action@v2
      #  with:
      #    username: ${{ secrets.DOCKERHUB_USERNAME }}
      #    password: ${{ secrets.DOCKERHUB_TOKEN }}

      #- name: Build and push
      #  uses: docker/build-push-action@v3
      #  with:
      #    context: .
      #    file: ./Dockerfile
      #    push: true
      #    tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.event.repository.name }}:0.0.1
